### ISSUE TITLE
This project needs more visibility

### ISSUE THREAD

**Issue by JulienItard** [symfony/symfony-demo#103]
Hi,
i think this project needs more visibility ! The official website never speaks about it. We should have a link to this repo in the homepage in Learn > Other ressources.
Also, we shoud have a link in the Documentation page in sidebar menu and in Symfony Best Practices section.

What do you think ? For now, beginners and others can't find this project if there are any link in the official website.

**Comment by javiereguiluz** [comment]
I agree with you, we need more visibility.

However, the project is already mentioned and explained in the docs: http://symfony.com/doc/current/book/installation.html#installing-the-symfony-demo-application

**Comment by bocharsky-bw** [comment]
I think this issue should be opened in [symfony-docs](https://github.com/symfony/symfony-docs) repo

**Comment by JulienItard** [comment]
Issue opened : https://github.com/symfony/symfony-docs/issues/5541

**Comment by javiereguiluz** [comment]
Closing it in favor of the `symfony-docs` issue.
