### ISSUE TITLE
Show post author and published date

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-demo#105]
Could we show post author and published date on blog page?

**Comment by JulienItard** [comment]
i'll do it.

**Comment by bocharsky-bw** [comment]
@javiereguiluz What do you think to show this fields on blog page?

**Comment by javiereguiluz** [comment]
I'd prefer to not display this information. It complicates site design for no real benefit :(

**Comment by JulienItard** [comment]
I think it's a good idea because we could show localizeddate date twig function to show how to translate date format.

**Comment by bocharsky-bw** [comment]
It's already done for comments in PR https://github.com/symfony/symfony-demo/pull/104

**Comment by JulienItard** [comment]
@bocharsky-bw Yes, it's true.

**Comment by javiereguiluz** [comment]
Now that #104 is merged, let's close this issue as "won't fix" for now. We'll revisit it in the future.

**Comment by yceruto** [comment]
Even when this is not a real blog, to have "published date" and "author" is IMHO an basic information for any article.

Perhaps some screenshots might motivate the reopening of this proposal :sweat_smile:

**Index Page:**
![post-index-metadata](https://cloud.githubusercontent.com/assets/2028198/21733937/f0843664-d42e-11e6-8a92-7363c35809e6.png)

**Show Page:**
![post-show-metadata](https://cloud.githubusercontent.com/assets/2028198/21734272/8b8784a8-d430-11e6-8d1b-263d501b4b64.png)

:heart_eyes:

**Comment by javiereguiluz** [comment]
@yceruto I've created #441 to implement your idea. Thanks!
