### ISSUE TITLE
Release application with dropdown to change locale

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-demo#113]
Could we add new tag to release application with localization dropdown in order to use via symfony installer?

**Comment by javiereguiluz** [comment]
Sure, but I'm waiting for a last merge related to fixing tests (partially broken precisely by the i18n). Besides, there are some Travis issues which I can't solve. I don't know if it's our fault, or Symfony's fault or Travis fault.

**Comment by bocharsky-bw** [comment]
Released in https://github.com/symfony/symfony-demo/releases/tag/v0.4.0

**Comment by javiereguiluz** [comment]
Just a quick comment to let you know that we're aware of some caching issues that prevent the new version to get installed when executing `symfony demo`. We'll fix it as soon as possible.

**Comment by bocharsky-bw** [comment]
Thanks for information
