### ISSUE TITLE
A week of symfony

### ISSUE THREAD

**Issue by JulienItard** [symfony/symfony-demo#115]
It would be great to have a *Symfony Demo highlights* such as *Silex development highlights*

=> more visibility, more PR

**Comment by javiereguiluz** [comment]
Insead of "hidding" these updates inside the "A week of Symfony" post, I prefer to highlight them in posts like the one we've just published: [The Symfony Demo application, three months later](http://symfony.com/blog/the-symfony-demo-application-three-months-later)
