### ISSUE TITLE
Change default port in Usage section

### ISSUE THREAD

**Issue by dosten** [symfony/symfony-demo#12]
Maybe is a good idea to change the default port in the Usage section of the README.md file because if you have apache or something listening in the same port the command returns
```
Server running on http://127.0.0.1:8000

Quit the server with CONTROL-C.
Built-in server terminated unexpectedly
Run the command again with -v option for more details
```
either with the `-v` flag the command returns
```
Server running on http://127.0.0.1:8000

Quit the server with CONTROL-C.
  RUN  '/usr/bin/php5' '-S' '127.0.0.1:8000' '/home/diego/develop/github/dosten/symfony-demo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php'
  RES  1 Command did not run successfully
Built-in server terminated unexpectedly
```
The error isn't very specific if the user has some tool listening in the port 8000.

**Comment by xabbuh** [comment]
@dosten This is the current behaviour of the `server:run` command from the Symfony FrameworkBundle. Do you mind opening an issue on the Symfony repository to improve the command feedback?

**Comment by weaverryan** [comment]
+1 to your suggestion @xabbuh

**Comment by dosten** [comment]
@xabbuh You are right, i see that the server:start command returns `A process is already listening on xxx`, i go to close this in favor of opening an issue in the symfony/symfony repo.

**Comment by javiereguiluz** [comment]
There was an old issue in the Symfony repository about this (see https://github.com/symfony/symfony/issues/10827). What I wanted is the `server:run` command to aumatically select the first free port starting from 8000. But that change didn't happen :(

**Comment by weaverryan** [comment]
@javiereguiluz It looks to me like that part of your suggestion may have just gotten buried and forgotten. I think that's an interesting idea (if no port is specified explicitly)

**Comment by xabbuh** [comment]
Indeed, I overlooked this when working on the other commands. However, I'm not sure if that really were desired behaviour. Wouldn't it be really confusing if you used several applications at the same time, the command chooses a port for you and you didn't notice? Then you open your browser and wonder why your changes don't have any effect.

**Comment by javiereguiluz** [comment]
@xabbuh my experience is the opposite: I use the `server:run` command a lot and I hate having to guess a free port number because I don't know how many opened applications I already have. I end up increasing in round numbers (`9000`, `10000`, etc.)

In an ideal world, `server:run` would do that work form me and it would provide me a port that always work :)

**Comment by xabbuh** [comment]
Maybe we should discuss this and, for example, add an option for this. I'm not really convinced, but I wouldn't have to use it. ;)
