### ISSUE TITLE
Ideas to improve demo app

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-demo#13]
Hi,

I've been checking this app as it will be soon the app I will show for new comers I work with (demo/initiation purpose).

If the idea of this app is to introduce basic stuff of Symfony, and moreover the best practices (so devs are going to check code+comments), I propose to add/change some data in it:

- add more comments where some "symfony magic" happen (like on https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Entity/Post.php#L161 to explain a minimum doctrine's relations) **=> comments lead to questions/answers which is good**
- a symfony command (a create:user with arguments/options to show a simple implementation, I have in mind the fos user's one, but in a minimal way) **=> symfony is as good in web as CLI**
- more?

**Comment by stof** [comment]
> lastly, add most common language translations? we want a lot of new comers

see #8 for that

**Comment by 94noni** [comment]
TY @stof for your comment, 
I've seen this issue before, but because nothing was clearly choosed (1 catalogue or 2), I preferred to post here (before doing the ``fr`` one for example)

Anyway, other feedbacks on the list?

**Comment by javiereguiluz** [comment]
@94noni thanks for these ideas:

1) We'll add a ton of help notes in the code, so you an consider it done.
2) Right now I'm creating a new `app:add-user` command. Thanks for your proposal. I love it.
3) As @stof said, I think it's better to discuss the specifics about this idea in #8

**Comment by stof** [comment]
@94noni No need to duplicate the discussion about translations, even though the decision is not taken yet. #8 clearly says that asking for translations in other languages is the last step of the issue resolution.

regarding comments, we should be careful about not duplicating the documentation though (duplication makes things really hard to maintain, and people will not think about updating comments in the demo app)

**Comment by 94noni** [comment]
@stof you're right, I removed the last item in the list

for the comments, they are already present in the app (with sometimes links etc) so I was just asking to improve/add some others for the "behind the scene" symfony logic
In fact, I propose this kind of idea due to the amount of comments I can see/deal with on blogs/forums where newcomers misunderstood these kind of logic, and I thought this demo source code could be a great idea to understand with code+minimal explications

Feel free to close this issue if considered as done :)

**Comment by javiereguiluz** [comment]
@94noni the command has been added in #14 so we can close this issue as fixed. But please, open new issues with any other idea you can come up. Thanks.
