### ISSUE TITLE
Pagination: third-party bundle or ...?

### ISSUE THREAD

**Issue by ccab** [symfony/symfony-demo#151]
IMO this project need the pagination feature for blog lists, in the FindLatest method we got a  Post::NUM_ITEMS but it isn't enough. What do we use for it I guess a third-party bundle right ?

**Comment by JulienItard** [comment]
Maybe we could use infinite scroll instead and explain how Ajax works too.

**Comment by javiereguiluz** [comment]
I prefer to not use infinite scroll. That way we can explain both Ajax and paginators separately.

For the paginator, my personal comment is that I always use Pagerfanta ... but I see that KnpPaginator is also very popular, so I don't mind which one is used.

**Comment by bocharsky-bw** [comment]
I don't like infinite scroll in this demo.

I don't ever used `PagerfantaBundle`, but if we talk about bundles, the `KnpPaginatorBundle` is most popular paginator for Symfony projects based on packagist and github statistic. It also allow sorting by fields out-of-the-box.

However if there are any strong reasons to use `PagerfantaBundle` instead - I'll not be against it.

**Comment by voronkovich** [comment]
We could implement both - a pagination and an infinite scroll, because many of infinite scroll plugins supports the pagination (with progressive enhancement). For example http://www.infinite-scroll.com/

**Comment by javiereguiluz** [comment]
@voronkovich I would prefer not to implement both. Our resources are limited, so let's keep doing the least amount of work which is useful :)

**Comment by ccab** [comment]
:+1:  for KnpPaginatorBundle I could create a PR for this one, what do you think ?
