### ISSUE TITLE
Add a RSS channel

### ISSUE THREAD

**Issue by ccab** [symfony/symfony-demo#155]
It could be interesting to add a channel in the frontend home page, so newcomers can see how to work with a new format

**Comment by JulienItard** [comment]
:+1:

**Comment by bocharsky-bw** [comment]
It would be interesting I think :+1:

**Comment by ccab** [comment]
Ok I got the idea to create a new template called `index.rss.twig` and made the minimal changes in the controller, including _format parameter to keep things simple, IMO a third-party bundle over-complicate this feature

**Comment by voronkovich** [comment]
@ccab, I think, you should create RssController

**Comment by javiereguiluz** [comment]
A new controller seems a bit overkill ... although perhaps there are solid reasons for doing it.

**Comment by ccab** [comment]
@voronkovich in my initial PR I just want to provide the frontend home page in RSS and I don't like to change the controller so much, maybe in the future don't you think ?

**Comment by voronkovich** [comment]
@ccab, @javiereguiluz, ok, let's wait for the PR

**Comment by javiereguiluz** [comment]
Closing it as fixed by #425.
