### ISSUE TITLE
Running without native intl generates 500

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-demo#157]
At least `/en/admin/post/` fails with the following error:

An exception has been thrown during the rendering of a template ("The Symfony\Component\Intl\DateFormatter\IntlDateFormatter::__construct() method's argument $locale value NULL behavior is not implemented. Only the locale "en" is supported. Please install the "intl" extension for full localization capabilities.")

**Comment by bocharsky-bw** [comment]
I seems already fixed, we waiting Symfony `v2.7.4` release.

Check https://github.com/symfony/symfony-demo/pull/123 for more info.

**Comment by stof** [comment]
We are indeed waiting for the 2.7.4 release to fix this issue in the demo.
