### ISSUE TITLE
[RFC] Adding other types of tests

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#172]
Right now we only provide some unit and functional tests. But in the real world, some developers are using BDD and other testing tools such as Codeception.

The Codeception guys have recently published [this article](http://codeception.com/09-04-2015/using-codeception-for-symfony-projects.html) about creating tests with their framework and the Symfony Demo application. They even forked the demo app to provide some tests ([see a sample test](https://github.com/Codeception/symfony-demo/blob/2.1/src%2FAppBundle%2Ftest%2Ffunctional%2FPostCrudCest.php)).

Should we include one sample Codeception, BDD, etc. test in our application? If those tools require to install some packages and do some config changes, we could just provide the test file and add a help note explaining how should developers install and configure that particular tool. That way the demo app would keep being simple, but at the same time, we would make it even more useful.

What do you think?

**Comment by bocharsky-bw** [comment]
I :+1: for BDD. It'll be useful. However I consider [Behat](http://docs.behat.org/en/v2.5/) as BDD tool.
Some reasons for it is that KnpUniversity already has excelent tutorial about [BDD, Behat, Mink and other Wonderful Things](http://knpuniversity.com/screencast/behat).

**Comment by voronkovich** [comment]
I :+1:  for Codeception, because "Unlike Behat, Codeception tests are written in PHP. Thus, they are more flexible and easy in writing". And it has more beautiful site than Behat :)

**Comment by bocharsky-bw** [comment]
However such famous developers in a Symfony world as stof, WouterJ, weaverryan, schmittjoh and docteurklein works on the Behat. I think it must mean something :)

**Comment by voronkovich** [comment]
Maybe you're right, @bocharsky-bw. I've found no open source Symfony projects that use the Codeception. Elcodi, Sylius and etc. use the Behat
Ok, I vote for the Behat too.

**Comment by rasanga** [comment]
My vote is for Behat

**Comment by javiereguiluz** [comment]
Closing it because this issue is too generic. We can discuss about this on a case-by-case basis.

Please note: if someone wants to submit new kinds of tests, please open an issue first to discuss about it. Thanks!
