### ISSUE TITLE
Refactor Twig extension names according to best practices guild

### ISSUE THREAD

**Issue by rasanga** [symfony/symfony-demo#176]
According to the Symfony2 best practices guild (http://symfony.com/doc/current/best_practices/templates.html#twig-extensions) twig extension naming convension would be the bundle name followed by underscore (_) and the extension name

ex: app_locale_extension (not app.locale_extension)

**Comment by bocharsky-bw** [comment]
Do you mean [this](https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Twig/AppExtension.php#L55) name?

**Comment by rasanga** [comment]
@bocharsky-bw 
Yes, and all 3 twig extension classes.

**Comment by bocharsky-bw** [comment]
Thank you @rasanga . I created PR for this https://github.com/symfony/symfony-demo/pull/177

**Comment by rasanga** [comment]
@bocharsky-bw :+1:

**Comment by bocharsky-bw** [comment]
Btw, I didn't find any suggestions about it in best practices, but we could see this usage in example further in [Twig Extensions](http://symfony.com/doc/current/best_practices/templates.html#twig-extensions) section, so I think we could proceed from this.

**Comment by rasanga** [comment]
Snake case is also used for form type and templating helper names so I guess it's good to have the same naming convension in twig extsion names as well.

**Comment by javiereguiluz** [comment]
I'd like to ask @weaverryan if he agrees to maintain the snake case (`app_extension`) for Twig extension names or if he prefers to change this best practice to use the same format as in services (e.g. `app.extension`). Thanks!

**Comment by stof** [comment]
well, the naming is currently consistent with form type naming (which will become irrelevant for Symfony 2.8 because of the form name refactoring). And most shared bundles are not using dots in the name (even though Twig does not put any restriction on it)

**Comment by weaverryan** [comment]
Yep, I like keeping the snake case practice, and I'm also fine if people want to remove the `_extension` - since you never again refer to this string.

**Comment by voronkovich** [comment]
@weaverryan, Should we avoid the name `AppExtension`? How to name it if we remove the `_extension`?

**Comment by rasanga** [comment]
Yes, I also prefer to remove _extension suffix from extension names because we do not use _type suffix for form types or _helper suffix for template helpers.

**Comment by bocharsky-bw** [comment]
Well, I renamed extension names without `_extension` suffix.

But I don't sure to get rid of `Extension` suffix in file name. In controllers we use `*Controller`, in forms -  `*Type`, in repositories - `*Repository`. Why don't follow this way for Twigextensions?

**Comment by rasanga** [comment]
I agree with you @bocharsky-bw on file names, it makes easier to browse files in IDEs.

**Comment by voronkovich** [comment]
@rasanga, ok, but I don't like class names like an `AppExtension` because this name means nothing

**Comment by rasanga** [comment]
@voronkovich yes AppExtension class does not make any sense so the class name should be re-factored to what does it actually mean to do. Hence, I would guess MarkdownExtension would be a better class name.

class name => MarkdownExtension
extension name => markdown

**Comment by voronkovich** [comment]
@rasanga, yes, and I think we should remove the comment:
"Consider using 'app.extension' if you only have one Twig extension in your application."

**Comment by bocharsky-bw** [comment]
I could also rename it in https://github.com/symfony/symfony-demo/pull/177 if @javiereguiluz approve idea to rename `AppExtension` to `MarkdownExtension`.

**Comment by weaverryan** [comment]
I disagree with renaming it. You're right that AppExtension doesn't tell you anything about what's inside (except the Extension part, which suggests it's a Twig Extension) - but that's ok - I usually have just 1 "AppExtension" with whatever Twig functions/filters I need for my "app". The sentence - "Consider using 'app.extension' if you only have one Twig extension in your application." - is suggesting exactly that: consider keeping things simpler and having just one extension.

**Comment by stof** [comment]
@weaverryan but we have more than just 1 extension here.

**Comment by rasanga** [comment]
Also class names should be specific when it's possible.

**Comment by weaverryan** [comment]
@stof Ah, so we do! Well, then I'm fine to rename it.

**Comment by javiereguiluz** [comment]
I have another proposal: let's forget about `SourceExtension` because it's very special and we even have a comment saying *"don't look at this extension"*.  The proposal: why don't we merge the LocaleExtension into the existing AppExtension?

**Comment by bocharsky-bw** [comment]
@javiereguiluz I like it more! It'll be better for simplicity

**Comment by javiereguiluz** [comment]
Closing it as fixed.
