### ISSUE TITLE
isValid checks whether submitted

### ISSUE THREAD

**Issue by frag-seb** [symfony/symfony-demo#183]
I think the duplicate check is unnecessary, isValid checks if isSubmitted.

```PHP
if ($form->isSubmitted() && $form->isValid()) {...}
```

example is here:

https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L83

**Comment by JulienItard** [comment]
Best pratices : 
Second, we recommend using $form->isSubmitted() in the if statement for clarity. This isn't technically needed, since isValid() first calls isSubmitted(). But without this, the flow doesn't read well as it looks like the form is always processed (even on the GET request).

**Comment by frag-seb** [comment]
I think the "isSubmitted" have only legitimation for 
```PHP
if(!isValid() && isSubmitted()) 
```
If you want to check something.

I'm assuming that it is submitted when it is vaild.

**Comment by xabbuh** [comment]
As @JulienItard said, the call to `isSubmitted()` is just made to make the intention more clear. It's perfectly valid to omit this call in your application, but the demo should comply with the best practices described in the documentation.

**Comment by bocharsky-bw** [comment]
https://github.com/symfony/symfony-demo/pull/49

**Comment by frag-seb** [comment]
Yes, it's alreasy. :D
