### ISSUE TITLE
Delete confirmation

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-demo#191]
Why not create a confirmation message before deleting a post?. Something like this:

**Option One:** Using javascript into html of the delete button:
```html
<input type="submit" value="Delete post" class="btn btn-lg btn-block btn-danger" onclick="confirm('Are you sure to delete this post?') || event.preventDefault()">
```
**Option Two**: Create a modal window using Twitter Bootstrap modal.
**Option Three**: Create a new page with the appropriate message. So, the current delete button was converted in an anchor to this page.

Or is there some reason why this behavior is not used?

**Comment by voronkovich** [comment]
I'd rather add a class 'confirmationable' for all links that require user confirmation, and simple listener for listening `onclick` event for those links.

**Comment by yceruto** [comment]
@voronkovich Good! Something like this:

```javascript
$('[data-toggle="confirmation"][data-message]').on('click', function (event) {
    var message = $(this).data('message');

    return confirm(message) || event.preventDefault();
});
```

**Comment by voronkovich** [comment]
@yceruto, yes, it is. It looks great!
