### ISSUE TITLE
Translation for sliding pagination controls

### ISSUE THREAD

**Issue by ccab** [symfony/symfony-demo#198]
The `KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig` template configured for pagination has `Previous` and `Next` strings ready for translation, what we should do: translate this strings directly or override this template and include new keys like `pagination.previous` & `pagination.next` ?

**Comment by bocharsky-bw** [comment]
I think better to use already defined keys: `next` and `previous`.

**Comment by ccab** [comment]
@bocharsky-bw where are these keys already defined ? I didn't see them in `messages.en.xliff`

**Comment by bocharsky-bw** [comment]
Sorry, I wrote with lowercase. It's the same what you mean first.

**Comment by ccab** [comment]
Ahh ok I also think it's better to overwrite this template and include this couple of keys

**Comment by ccab** [comment]
Where should be included this keys inside the dictionary ? As simple keys or in title, action or label sections ?
