### ISSUE TITLE
How to name the services?

### ISSUE THREAD

**Issue by voronkovich** [symfony/symfony-demo#200]
We use `app.twig.locale_extension` for a twig extension, but for a listener we use `app.controller_listener` instead of `app.listener.controller_listener` or `app.listener.controller`.

**Comment by bocharsky-bw** [comment]
I use `app.twig_extension.locale` for `App\TwigExtension\LocaleExtension` and `app.event_listener.controller` for `App\EventListener\ControllerListener` names. For second part I use directory name in bundle and third without suffix. I think thit way I can easy group them.

**Comment by voronkovich** [comment]
@bocharsky-bw, I would prefer `app.twig.locale_extension`  and `app.event_listener.controller_listener`
The rule: `bundle_prefix.namespace.class_name_without_suffix`

**Comment by javiereguiluz** [comment]
There is a "best practice" recommendation for this: http://symfony.com/doc/current/best_practices/business-logic.html#services-naming-and-format

There is no need to put `listener` or `event_listener` in the middle of the service name. If this app had 2,000 services, we would do that of course :)

**Comment by voronkovich** [comment]
@javiereguiluz `app.repository.user` and `app.user_repository` have the same length, but I would prefer the first variant. The same for the `app.listener.controller` and `app.controller_listener`.

**Comment by javiereguiluz** [comment]
Closing it for now without making any change. But we'll revisit this decision when/if we add lots of new services. Thanks.
