### ISSUE TITLE
[Show code] Twig template code no shown when clear cache

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-demo#224]
when I clean the cache the twig template code is not shown in the modal window.

Debugging `Twig_Template` class:
```php
/**
 * Returns the template source code.
 *
 * @return string|null The template source code or null if it is not available
 */
public function getSource()
{
    $reflector = new ReflectionClass($this);
    $file = $reflector->getFileName();

    if (!file_exists($file)) {
        return;
    }

    //...
}
```

The `$reflector->getFileName()` returns `..\vendor\twig\twig\lib\Twig\Environment.php(390) : eval()'d code` and finally `getSource()` returns `null`:

![twig-template-code](https://cloud.githubusercontent.com/assets/2028198/10436332/b7ee41d6-70f3-11e5-982a-cfde046a2282.png)

This happen the first time after clear cache for each twig template. Any idea what might be happening?

**Comment by stof** [comment]
This looks like an issue in Twig itself

**Comment by yceruto** [comment]
I think so @stof

**Comment by javiereguiluz** [comment]
It may be related to this? https://github.com/symfony/symfony/pull/15034

**Comment by javiereguiluz** [comment]
@yceruto could we close this issue or are you still suffering it? Thanks!

**Comment by voronkovich** [comment]
@javiereguiluz, the error is still occurs
https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L333

**Comment by yceruto** [comment]
@javiereguiluz, still occurs :(

**Comment by stof** [comment]
@javiereguiluz I think this is because Twig does not load the cache file but evals the code when the cache does not exist yet

**Comment by javiereguiluz** [comment]
I've reported this error in the Twig repo: https://github.com/twigphp/Twig/issues/2011
