### ISSUE TITLE
Unused local variable

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-demo#225]
Unused local variable `formattedCode`. The value of the variable is overwritten immediately.

https://github.com/symfony/symfony-demo/blob/master/src/CodeExplorerBundle/Twig/SourceCodeExtension.php#L123

**Comment by bocharsky-bw** [comment]
I would like to replace it with `$formattedCode = $code;` on line 123 and get rid of `else` on https://github.com/symfony/symfony-demo/blob/master/src/CodeExplorerBundle/Twig/SourceCodeExtension.php#L133-L135

**Comment by voronkovich** [comment]
@bocharsky-bw, I agree with you.

**Comment by yceruto** [comment]
:+1: @bocharsky-bw
