### ISSUE TITLE
Comment in src/CodeExplorerBundle/Resources/views/source_code.html.twig contradicts file name

### ISSUE THREAD

**Issue by frankadrian** [symfony/symfony-demo#227]
The comment states that fragments should be prefixed with an underscore. Is this just a typo in the file name?

**Comment by voronkovich** [comment]
@frankadrian, this file was moved from the AppBundle. I think we should remove that comment.

**Comment by javiereguiluz** [comment]
Yes. The comment should be removed. Thanks.
