### ISSUE TITLE
Location of doctrine repositories

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-demo#24]
I just found out that repositories live in `AppBundle\Repository` in this demo app. However, in the docs we use `AppBundle\Entity` (see https://github.com/symfony/symfony-docs/issues/1316 for some context for this decision).

We should choose one and update either the demo app or the generator and docs.

**Comment by stof** [comment]
Keeping it in ``AppBundle\Repository`` is better IMO. It avoids having Doctrine looking for metadata on it when asking for the list of metadata, and repositories and entities are 2 different concepts.

The choice for the doc was based on a limitation of the repository generator command (which is not very useful anyway as it is only about creating an empty class). We should rather update the generator command (the generator in Doctrine ORM is happy to generate it for any namespace btw)

**Comment by xelaris** [comment]
I also prefer to have the repositories in a separate namespace. Please have a look at https://github.com/sensiolabs/SensioGeneratorBundle/pull/342 where I propose a corresponding update to the generator command.

**Comment by weaverryan** [comment]
I've wanted this change for awhile, but for some reason (which I can't think of now), I thought I had dreamt up some disadvantage. But since I can't remember, +1 for making the change in SensioGeneratorBundle and then updating the docs.

**Comment by javiereguiluz** [comment]
I'm closing this issue because most people seem to agree on the `Repository/` location for repositories. 

@xelaris I wish your proposal is accepted and merged soon. Thanks.
