### ISSUE TITLE
Don't use the deprecated "_self" variable in Twig templates

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#242]
When running tests, I get 4 deprecation notices:

```
Remaining deprecation notices (4)

Global variable "_self" is deprecated in ? at line 87: 1x
    1x in DefaultControllerTest::testPublicUrls from AppBundle\Tests\Controller

Global variable "_self" is deprecated in ? at line 62: 1x
    1x in DefaultControllerTest::testPublicUrls from AppBundle\Tests\Controller

Global variable "_self" is deprecated in ? at line 28: 1x
    1x in BlogControllerTest::testIndex from AppBundle\Tests\Controller

Global variable "_self" is deprecated in ? at line 57: 1x
    1x in BlogControllerTest::testAdministratorUsersCanAccessToTheBackend from AppBundle\Tests\Controller\Admin
```

The reason is that our templates use this code:

```twig
{{ show_source_code(_self) }}
```

The `_self` variable is deprecated and it will be removed in Twig 2.0. We need to replace it by:

```twig
{{ show_source_code() }}
```

But then, inside the Twig extension I don't know how to get the name or path or code of the template that called the `show_source_code()` function.

**Comment by xabbuh** [comment]
Can't you pass `current` instead of `_self`?

**Comment by javiereguiluz** [comment]
I don't understand you. Like this?

```twig
{{ show_source_code(current) }}
```

**Comment by xabbuh** [comment]
yes

**Comment by javiereguiluz** [comment]
I still don't understand :disappointed:  The `current` variable doesn't exist anywhere.

**Comment by xabbuh** [comment]
Hm, seems that you can use `current` only for macros.

**Comment by javiereguiluz** [comment]
Somewhat related to this, I have the following in a Symfony application:

```twig
{% form_theme form _self %}
```

What would be the equivalent now that `_self` is deprecated?

**Comment by stof** [comment]
@javiereguiluz I will try to find a way to refactor the display of the source code to avoid relying on ``_self``. but it will wait until this evening

**Comment by voronkovich** [comment]
I think we could just replace the `_self` instances in the templates by actual files names, like this:

```twig
{{ show_source_code('blog/edit.html.twig') }}
...
{{ show_source_code('@XyzBundle/x/y/z.html.twig') }}
...
{% form_theme form 'admin/blog/edit.htm.twig' %}
```

**Comment by javiereguiluz** [comment]
@voronkovich yes, but that would be SO boring!! Let's wait for the solution that will propose @stof. In any case, there is no need to hurry. This variable won't stop working until Symfony 3.0.

**Comment by stof** [comment]
@javiereguiluz not Symfony 3.0, but Twig 2.0. Symfony 3 is still compatible with Twig 1 (and Twig 2 is not yet stable)

**Comment by fabpot** [comment]
This one can be closed as `_self` has been un-deprecated now.

**Comment by javiereguiluz** [comment]
Great!
