### ISSUE TITLE
Fix the Form component deprecations for Symfony 3

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#250]
If you try to create a new blog post (`/en/admin/post/new`):

![admin_post_create](https://cloud.githubusercontent.com/assets/73419/11238637/4c8fbba2-8de7-11e5-8d54-32e1ba53b35b.png)

If you try to edit a blog post (`/en/admin/post/1/edit`):

![admin_post_edit](https://cloud.githubusercontent.com/assets/73419/11238650/62c5fec2-8de7-11e5-8a7b-e01f215077ec.png)

**Comment by bocharsky-bw** [comment]
Can you describe how to reproduce it? You update `symfony/symfony` to `v3.0.0-BETA1`?

**Comment by stof** [comment]
@bocharsky-bw yeah. In 2.8 you would get a deprecation warning instead of an exception

**Comment by javiereguiluz** [comment]
@bocharsky-bw the easiest way to update is to copy the `composer.lock` from here: https://github.com/benji07/symfony-demo/tree/symfony3  and execute a `composer install`
