### ISSUE TITLE
Fix the deprecations related to ResourceInterface::isFresh()

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#251]
I'm not sure if we can fix this in our own code, but it's producing lots of deprecation messages:

![resource_isfresh_deprecations](https://cloud.githubusercontent.com/assets/73419/11238996/a98a280e-8de9-11e5-99f6-b2cd2693fc25.png)

**Comment by bocharsky-bw** [comment]
Hm, I haven't any deprecations on `/en/blog/` related with `ResourceInterface::isFresh()`.

**Comment by bocharsky-bw** [comment]
Seems it's a core and it'll be fixed in Symfony 3.0 without us.

**Comment by stof** [comment]
We should update the deprecation message to say which class triggered it.

But this is probably related to AsseticBundle. Try again with the dev version as a fix has been merged a few days ago

**Comment by ogizanagi** [comment]
I confirm this is fixed using dev version of the AsseticBundle.

**Comment by javiereguiluz** [comment]
@ogizanagi great!

**Comment by stof** [comment]
AsseticBundle will be released this weekend (or before)

**Comment by javiereguiluz** [comment]
Closing it because the error clearly comes from Assetic and it will be fixed soon:

![assetic_deprecations](https://cloud.githubusercontent.com/assets/73419/11865824/ecaf51bc-a4a6-11e5-92d1-0df3b96bc2bf.png)

**Comment by WouterJ** [comment]
@stof there is no new release of AsseticBundle yet, any ideas when it's coming?

**Comment by stephanvierkant** [comment]
@WouterJ Follow this issue to see when it's fixed: https://github.com/symfony/assetic-bundle/issues/401

**Comment by stephanvierkant** [comment]
Still no update from @stof. @WouterJ, do you know why it takes so long (even to explain it)?
