### ISSUE TITLE
Add description to this repo

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-demo#263]
Why we haven't any description of this [repo](https://github.com/symfony/symfony-demo):
> No description or website provided.

![no-desc](https://cloud.githubusercontent.com/assets/3317635/11497291/aa9c56d6-9820-11e5-88a7-8aafaad64227.jpg)

We could get some description from README file and also add a link to the symfony.com for it.

**Comment by benakacha** [comment]
ok

**Comment by bocharsky-bw** [comment]
@javiereguiluz Any thoughts about it?

**Comment by bocharsky-bw** [comment]
Already done!
