### ISSUE TITLE
The project uses a totally outdated version of erusev/parsedown

### ISSUE THREAD

**Issue by stof** [symfony/symfony-demo#27]
It would be better to use an uptodate version (we should encourage people to use maintained versions of their dependencies)

**Comment by mseshachalam** [comment]
what about using https://github.com/thephpleague/commonmark ?

**Comment by javiereguiluz** [comment]
Fixed as of 527a33e

@mseshachalam in the future we'll consider changing the Markdown library. For now, `parsedown` works right for us, is much faster and much more popular.
