### ISSUE TITLE
Assetic issue / sass compiling + icon fonts retrieval

### ISSUE THREAD

**Issue by nska02** [symfony/symfony-demo#295]
Hi,

I just tried to run (with built-in php server) the demo with Assetic compiling the provided scss/js files.
There seems to be issues on bootstrap compiling and fontawesome icons retrieval.
On the other hand (assetic-less = just css and js), this works fine.

Specific assetic issue or...? I would assume you tested the demo with assetic compiling.

Any idea?
Thanks.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #318.
