### ISSUE TITLE
Null value not valid for setPost function parameter

### ISSUE THREAD

**Issue by jesusronu** [symfony/symfony-demo#302]
- File: src\AppBundle\Entity\Post.php
- Line: 171
- Function Code:
```
public function removeComment(Comment $comment)
    {
        $this->comments->removeElement($comment);
        $comment->setPost(null);
    }
```
PHP doesn't accept null value for a type-hinting parameter (you can set default value to null but it seems a workaround not a real solution in my opinion).

Result: ContextErrorException, Catchable Fatal Error: Argument 1 passed to AppBundle\Entity\Comment::setPost() must be an instance of AppBundle\Entity\Post, null given, called in ...

PHP: 5.6.15 using included web server

Excuse my poor english.

**Comment by bocharsky-bw** [comment]
@jesusronu Thank you for this bug report!

Actually, it's pointless to set `Post` to `null` here as we have OneToMany relation (Post => Comments) and fully remove Comment from DB with `removeComment()` method.
