### ISSUE TITLE
Replace KnpPaginatorBundle by PagerfantaBundle

### ISSUE THREAD

**Issue by voronkovich** [symfony/symfony-demo#305]
KnpPaginatorBundle has some bad parts:

- It doesn't support the translation https://github.com/KnpLabs/KnpPaginatorBundle/issues/334
- It has a bug with the pagination https://github.com/KnpLabs/knp-components/issues/78
- IMO: it has a very ugly design

I tried to fix the first issue here https://github.com/symfony/symfony-demo/pull/304, but I think it's better to get the rid of KnpPaginatorBundle at all.

**Comment by javiereguiluz** [comment]
I don't like KnpPaginator and I always use Pagerfanta instead ... but I don't have strong arguments against KnpPaginator (except for the lack of i18n). Let's see what do others think about this.

**Comment by bocharsky-bw** [comment]
As I investigated, KnpPaginator has much more opened issues and PRs than PagerfantaBundle. Looks like KnpPaginator maintenance is much slower, so I'm fine to get rid of it favor of PagerfantaBundle :+1: .

**Comment by stof** [comment]
I also prefer the way Pagerfanta handles pagination compared to KnpPaginator (trying to make a single paginator service which would guess how to paginate the data is weird, as the caller almost always knows what it wants to paginate).
So my vote would be to use Pagerfanta (it was already my preference when talking about adding pagination in the first place btw)

**Comment by krewetka** [comment]
Pager was not using translations and was only in English.

I create PR for that https://github.com/symfony/symfony-demo/pull/332

Proably also strings ( previous and next) could be now removed from translation as the one from PagerFanta are used?

**Comment by voronkovich** [comment]
@krewetka, you're right. Please, create a PR with deleted `previous` and `next` strings.

**Comment by krewetka** [comment]
I'm not really good with proper PR done from browser ;)

I accidentally added changes to the same PR ( and forgot proper description in 2 files)

https://github.com/symfony/symfony-demo/pull/332

Hope it's ok :) Don't really have time now to start again.
