### ISSUE TITLE
Issue with MySQL installation of symfony-demo

### ISSUE THREAD

**Issue by jzawadzki** [symfony/symfony-demo#309]
Hi! 

When @dzuelke prepared symfony-demo app for heroku, he introduced additional db configuration in `config_dev.yml` as a workaround for doctrine bug: https://github.com/symfony/symfony-demo/blob/master/app/config/config_dev.yml#L13

However this creates a problem when user is trying to change default db from sqllte to mysql. In such case user should remove those lines as those assume they are using standard sqllte db.

I think it would be good to put some additional info to `parameters.yml` (near https://github.com/symfony/symfony-demo/blob/master/app/config/parameters.yml.dist#L11) so user would know that he must also change `config_dev.yml` until the bug is resolved on doctrine side.

JZ

**Comment by bocharsky-bw** [comment]
:+1:

**Comment by voronkovich** [comment]
Agreed :+1:

**Comment by javiereguiluz** [comment]
Closing it as fixed by #310
