### ISSUE TITLE
Update readme to clarify that latest symfony installer is required

### ISSUE THREAD

**Issue by yahuarkuntur** [symfony/symfony-demo#31]
I was using the 1.0.0 version of the symfony installer, and issuing the command:
```
$ symfony demo
```
resulted in:
```
[InvalidArgumentException]      
Command "demo" is not defined.
```
I know that the latest version of the symfony installer must be used, but, can it be specified better in the README?

Best regards,

**Comment by javiereguiluz** [comment]
@yahuarkuntur thanks for opening this issue. I've just updated [the installation section](https://github.com/symfony/symfony-demo#installation) of the README.

In the future we'll remove this note about updating the installer in case you don't have the `demo` command, but I agree that it makes sense to add it now that the installer is pretty new.
