### ISSUE TITLE
Running composer install leaves the project in a dirty state

### ISSUE THREAD

**Issue by stof** [symfony/symfony-demo#314]
There is a composer hook updating the requirement file, but it also updates ``web/config.php``, while the demo has a customized version.
This makes it harder to contribute as we have to remember to undo the updates all the time.

**Comment by dunglas** [comment]
What do you think about renaming the customized file to something like `web/demo-config.php`?

**Comment by bocharsky-bw** [comment]
@dunglas IIRC, the reason why we didn't rename it was that [app/check.php](https://github.com/symfony/symfony-demo/blob/master/app/check.php#L71) references to the `web/config.php` file, so renaming this file to something different will be confusing.

**Comment by dunglas** [comment]
We can also introduce a `app/check-demo.php`.

**Comment by bocharsky-bw** [comment]
Yes, but then we need to get rid of [ScriptHandler::installRequirementsFile](https://github.com/symfony/symfony-demo/blob/master/composer.json#L40) in Composer's post install and post update commands. In this case, we reject DistributionBundle requirements, so we need to support them manually.

**Comment by stof** [comment]
@bocharsky-bw we would still need to update the requirements file, as we want to have an uptodate one in the demo

**Comment by javiereguiluz** [comment]
I'd say ... let's remove the customized `web/config.php` file and forget about this problem forever.

**Comment by bocharsky-bw** [comment]
Could we keep original `web/config.php` instead of customized?

**Comment by javiereguiluz** [comment]
@bocharsky-bw yes. I meant removing our modifications and leave whatever Symfony provides.

**Comment by bocharsky-bw** [comment]
@javiereguiluz Looks like it's the easiest way :+1:

**Comment by dunglas** [comment]
:+1+: for Javier suggestion too.
