### ISSUE TITLE
In Twig 2.x, _self is a string instead of a Template instance

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#322]
In the templates of this application we use the following to display the source code of the current Twig template:

```twig
{{ show_source_code(_self) }}
```

However, Twig 2.x changed the `_self` variable and now it only returns a string of the template path instead of the `Template` object instance.

We should change/improve this feature to make the application compatible with Symfony 3.

**Comment by voronkovich** [comment]
As a solution I would suggest https://github.com/symfony/symfony-demo/pull/254, because for now `_self` is useless and looks very strange for the newcomers.

**Comment by stof** [comment]
Title is wrong. It is about Twig 2. Migrating to Symfony 3 has nothing to do here

**Comment by stof** [comment]
@voronkovich there is a much simpler way. See my PR.
