### ISSUE TITLE
Symfony installer pulls old symfony demo version

### ISSUE THREAD

**Issue by sargath** [symfony/symfony-demo#327]
FYI I'm posting this here also

https://github.com/symfony/symfony-installer/issues/240

**Comment by javiereguiluz** [comment]
@sargath you are right. Sadly I cannot give you details why ... but I hope this will be fixed sooner than later. Thanks for your patience.

**Comment by javiereguiluz** [comment]
I'm glad to close this issue as "fixed". Execute `symfony demo` command and you'll get the shiny new Symfony Demo version :tada:

**Comment by sargath** [comment]
referring comment https://github.com/symfony/symfony-installer/issues/240#issuecomment-204008530, still not work on linux OS

**Comment by sargath** [comment]
@javiereguiluz

**Comment by sargath** [comment]
@javiereguiluz I think from today it is OK, now the right version is being downloaded, thx

**Comment by sargath** [comment]
@javiereguiluz seems that problem still exist, your updates doesn't exist in demo while using symfony installer for instance changes with new paginator.

**Comment by javiereguiluz** [comment]
@sargath the new versions need some time to propagate through the CDN caches. For now I consider this is working ... but I'll keep monitoring this.

**Comment by sargath** [comment]
@javiereguiluz  aha ok, sorry for officiousness :) regards
