### ISSUE TITLE
Add viewport meta tag for mobile support

### ISSUE THREAD

**Issue by CesarManriqueH** [symfony/symfony-demo#330]
I was testing this project on my phone and realized that it's not reponsive because the viewport meta tag is not defined.
As bootstrap is being used adding support for mobiles is pretty easy.
After the viewport is defined this looks really good.

**Comment by xabbuh** [comment]
@CesarManriqueH Thank you for your feedback. Would you like to create a pull request with the needed changes?

**Comment by CesarManriqueH** [comment]
Sure! I just did it :D

**Comment by javiereguiluz** [comment]
Closing it as fixed by #331.
