### ISSUE TITLE
Add an example of using dump()

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-demo#339]
The best way to make this nice function easily discoverable :)

**Comment by voronkovich** [comment]
@nicolas-grekas, do you mean the Twig's `dump` function: http://twig.sensiolabs.org/doc/functions/dump.html?

**Comment by weaverryan** [comment]
@voronkovich sort of - but in the Symfony Framework, you can use `dump()` in php code as well - it's from the VarDumper component. That's what Nicolas is talking about here:

```php
dump($someVar);
```

**Comment by voronkovich** [comment]
@weaverryan, thanks for the explanation! I think we could just dump a list of posts to the web toolbar in a homepage's controller and add a comment explaining this feature
