### ISSUE TITLE
Integrate javiereguiluz/slugger

### ISSUE THREAD

**Issue by dosten** [symfony/symfony-demo#34]
I have seen the code of the slugger of @javiereguiluz and it's pretty good, what is the current state of the code? What do you think about integrate it into the demo?

**Comment by javiereguiluz** [comment]
@dosten thanks for opening this issue to propose improvements for the Symfony Demo application.

To be completely honest, I don't think we should integrate any external library to generate slugs. The main reason is that this application should stay as simple as possible, and adding dependencies always complicate things. The second reason is that being a simple application, we won't need to generate slugs for non-lating alphabets or SEO-enhanced slugs, so there is no technical justification to add a library to handle those cases.

I'm leaving this issue open for the moment, in case anyone wants to discuss about the possibility of integrating external dependencies in the demo application (not for slugs, but for other features). Thanks!

**Comment by javiereguiluz** [comment]
Closing it because for the moment no one feels the necessity of integrating other third-party libraries in the application.
