### ISSUE TITLE
Add an example for RequireJS use

### ISSUE THREAD

**Issue by jabranr** [symfony/symfony-demo#345]
Here is a use case. It would be great to have an example on how to combine all modules required in this use case for production use. Thank you.

##### `.../views/Default/index.html.twig`:
``` html
{% block javascripts %}
  <script 
    data-main="{{ asset('bundles/foobarbundle/js/main') }}" 
    src="'path/to/require.js'">
  </script>
{% endblock %}
```
##### `bundles/foobarbundle/js/main.js`:
``` javascript
require([
  './partials/foo', 
  './partials/bar'
], function(foo, bar) { });
```

---

##### `.../views/Default/foo.html.twig`:
``` html
{% block javascripts %}
  <script 
    data-main="{{ asset('bundles/foobarbundle/js/foo') }}" 
    src="'path/to/require.js'">
  </script>
{% endblock %}
```
##### `bundles/foobarbundle/js/foo.js`:
``` javascript
require([
  'jquery',
  './partials/baz'
], function($, baz) { });
```

**Comment by javiereguiluz** [comment]
@jabranr thanks for this proposal! To be honest, I'm not sure about it because this is a demo application to showcase Symfony features. This looks "too JavaScript" to me.

**Comment by jabranr** [comment]
@javiereguiluz Thanks for replying. I am afraid yes it does sound like one. But the request was meant to be more like how it can be done in *Symfony* as there are no public resource on web about this. I am not sure if that strengthens the case. :)

**Comment by xabbuh** [comment]
@jabranr Can you please explain what from your point of view is special about using require.js in a Symfony project compared to any other web application? As it stands I would agree with Javier on this not being Symfony specific enough to become part of the demo.

**Comment by javiereguiluz** [comment]
@jabranr we want to add more tutorials about Symfony + JavaScript (see https://github.com/symfony/symfony-docs/issues/6285) but we are failing at getting people involved in this task.

**Comment by jabranr** [comment]
@xabbuh Nothing special in this. Basically it meant to expand the demo to cover various type of cross-technology integrations.

@javiereguiluz Well!

I am aware that there is a [bundle](https://github.com/hearsayit/HearsayRequireJSBundle) for this but the efforts it takes to configure the bundle to work is somewhat tedious. A basic setup would be much more useful in terms of learning.

**Comment by javiereguiluz** [comment]
Let's close this for now as "won't fix". If we start expanding the demo to add JavaScript features, people will start asking to integrate other common technologies, such as Redis, and the demo will complicate too much. @jabranr thanks for your proposal and thanks for understanding this decision.

**Comment by jabranr** [comment]
@javiereguiluz Totally understand that. Thanks for the inputs.
