### ISSUE TITLE
Git Command for symfony-demo 2.8 version

### ISSUE THREAD

**Issue by ashishkatoch** [symfony/symfony-demo#369]
Hello There,

I want to install 2.8 version of symfony demo except than 3.0 version.

Are these git commands use for 2.8 ?

$ git clone https://github.com/symfony/symfony-demo
$ cd symfony-demo/
$ composer install --no-interaction

Regards
Ashish K

**Comment by voronkovich** [comment]
@ashishkatoch , use `git checkout tags/v0.8.4` before calling `composer install`

**Comment by javiereguiluz** [comment]
@ashishkatoch as you probably know, we can't make this demo application compatible with Symfony 2.8 and 3.x at the same time. However, we could improve the documentation for those who want to run the 2.8 compatible app. That's what we're trying to do in #370. Could you please check if those instructions work for you as expected? Thanks a lot!

**Comment by andrerom** [comment]
Can be closed now

**Comment by javiereguiluz** [comment]
Closing it as fixed.
