### ISSUE TITLE
Deploy to heroku is broken.

### ISSUE THREAD

**Issue by dmnian** [symfony/symfony-demo#371]
Hello,

1. I opened readme and click deploy button;
2. I filled form.
3. I saw error in log. 

Log from heroku:
http://pastebin.com/rFbSNUqv
I want to highlight a line:

> An exception occurred while executing 'CREATE TABLE symfony_demo_user (id I  [39;49m
>  
> [37;41m  NTEGER NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NUL  [39;49m
>  
> [37;41m  L, password VARCHAR(255) NOT NULL, roles CLOB NOT NULL, PRIMARY KEY(id))':   [39;49m
>  
> [37;41m  SQLSTATE[HY000]: General error: 1 table symfony_demo_user already exists  

Thanks in advance

**Comment by javiereguiluz** [comment]
@dmnian I'm afraid that you are right ... but I don't know how to solve it. If we fix Heroku ... we break the Symfony Demo for non-Heroku users and viceversa. The main issues are the Doctrine database configuration and the log files.

**Comment by stof** [comment]
@javiereguiluz you could use ``doctrine:schema:update`` rather than ``doctrine:schema:create``. It will be a bit slower (as it will check the existing schema), but it will create tables only when they don't exist

**Comment by stof** [comment]
ah no, this is related to moving back to separate params rather than the url

**Comment by dzuelke** [comment]
So the fix in #377 doesn't really resolve it. @stof can you explain what is or was broken here? Can we clean it up again, especially now that #390 is merged and with 3.2's dynamic env vars possibly around the corner?

**Comment by dzuelke** [comment]
Btw @javiereguiluz feel free to always ping me for any Heroku related issues!
