### ISSUE TITLE
Use HTMLPurifierBundle instead of standalone HTMLPurifier

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-demo#374]
We got rid of possible XSS injection in https://github.com/symfony/symfony-demo/pull/146 with [ezyang/htmlpurifier](https://github.com/ezyang/htmlpurifier) standalone library and then have some trouble with caching which we fixed in https://github.com/symfony/symfony-demo/pull/282.

What do you think about to do it in a more Symfony-oriented way and replace ezyang/htmlpurifier with the [Exercise/HTMLPurifierBundle](https://github.com/Exercise/HTMLPurifierBundle) bundle?

**Comment by stof** [comment]
ExerciseHTMLPurifierBundle only configures a service for you. It suffers from exactly the same issues.

**Comment by voronkovich** [comment]
I agree with @stof. If we will use that bundle we will need to disable the caching to avoid problems with files permissions.

**Comment by bocharsky-bw** [comment]
My point here is to use a bundle instead of a standalone library in Symfony Demo if it makes sense.

**Comment by stof** [comment]
@bocharsky-bw featurin the usage of standalone libraries is good as well, when there is no benefit of using a dedicated bundle for that. Pushing people to think that they need a bundle for everything is a bad idea IMO, as many issues can be solved by generic libraries.

**Comment by javiereguiluz** [comment]
Not directly related to this issue ... but I'm worried about the time it takes to "purify" contents.

For a blog post view page (e.g. http://127.0.0.1:8000/app.php/en/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit) the HTML_Purifier thing takes more than 30% of total time, around 30 ms., and executes hundreds of PHP functions:

![profile_html_purify](https://cloud.githubusercontent.com/assets/73419/18132310/9d982e76-6f96-11e6-9c48-e30109fd9ead.png)

**My question:** is this process necessarily slow and we cannot do anything about that ... or should we explore faster solutions to this problem? Thanks!

**Comment by voronkovich** [comment]
@javiereguiluz, it happens because we disabled the caching. I think we can't fix this for now.

**Comment by javiereguiluz** [comment]
Let's close this issue as "won't fix". @stof is right and it's OK to show an example of integrating libraries without bundles.
