### ISSUE TITLE
Fatal error: Cannot redeclare class Symfony\Component\HttpFoundation\Response (or ResponseHeaderBag)

### ISSUE THREAD

**Issue by ieleja** [symfony/symfony-demo#411]
OSX, Apache 2.4, PHP 5.6.27
Linux, Apache 2.4, PHP 5.6.28

clean Symfony Demo install with:
$ symfony demo

point browser to:
http://localhost/symfony_demo/web/en/blog/

choose:
Browse Application
Back to blog

and always get this Fatal error under OSX:
PHP Fatal error:  Cannot redeclare class Symfony\\Component\\HttpFoundation\\ResponseHeaderBag in /Users/User/Sites/symfony_demo/var/cache/prod/classes.php on line 4491
or
PHP Fatal error:  Cannot redeclare class Symfony\\Component\\HttpFoundation\\Response in /Users/User/Sites/symfony_demo/var/cache/prod/classes.php on line 3777
and under Linux:
PHP Fatal error:  Cannot redeclare class Symfony\\Component\\HttpFoundation\\ResponseHeaderBag in /var/www/symfony_demo/var/cache/prod/classes.php on line 4491

clearing cache helps exactly one time, up to server recreates cache files

error reproduces in Chrome, Firefox, Safari

**Comment by bocharsky-bw** [comment]
What version of `symfony/symfony` do you use?

**Comment by voronkovich** [comment]
@ieleja, do you clean the cache manually, without warmup? Try to use `php bin/console cache:clear --env=prod --no-debug`.

**Comment by ieleja** [comment]
bash-3.2$ bin/console --version
Symfony 3.2.0 (kernel: app, env: dev, debug: true)

==============

bash-3.2$ php bin/console cache:clear --env=prod --no-debug

 // Clearing the cache for the prod environment with debug false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

==============

after few successful clicks on Login/Logout/Homepage I get again:

PHP Fatal error: Cannot redeclare class Symfony\Component\HttpFoundation\Response in /Users/User/Sites/symfony_demo/var/cache/prod/classes.php on line 3777
and
HP Fatal error: Cannot redeclare class Symfony\Component\HttpFoundation\ResponseHeaderBag in /var/www/symfony_demo/var/cache/prod/classes.php on line 4491

p.s.
macOS, Debian Linux, Chrome, Firefox is up-to-date

**Comment by RenWasHere** [comment]
Same issue in Symfony 3.2.1.

Clearing the cache does fix it until you load another page.

PHP 7.0.10
Apache 2.4.23
MySQL 5.7.14
Windows 10 Pro

**Comment by bocharsky-bw** [comment]
I'm getting the same issue on PHP 7.0 and 7.1

**Comment by javiereguiluz** [comment]
I can't reproduce with latest Symfony Demo + Symfony 3.2.1 + PHP 7.1.

Please, tell me the exact steps to reproduce it:

1. `$ symfony demo`
2. `$ cd symfony_demo`
3. `php bin/console server:start`
4. Browse `127.0.0.1:8000`
5. ...

**Comment by bocharsky-bw** [comment]
@javiereguiluz It works for me only with the `prod` environment. My steps to reproduce are:

1. Clone repo (the latest master commit)
2. `composer ins`
3. `bin/console s:r`
4. `rm -rf var/cache/*`
5. Browser http://127.0.0.1:8000/app.php/
6. Press "Browser application"
7. Press "Symfony Demo"
8. Press "Browser application" again
9. If you don't see "Fatal error..." - repeat 6-8 steps

Anyway, for me, this error happens only on blog list page, i.e. when surfing Symfony Demo app and return to the http://127.0.0.1:8000/app.php/ru/blog/ page

**Comment by javiereguiluz** [comment]
@bocharsky-bw thanks! I could reproduce it now. They key for me was: use the `prod` environment and repeat the navigation several times until this error appears:

![symfony-demo-error](https://cloud.githubusercontent.com/assets/73419/21519068/bd20dbce-ccea-11e6-892b-1aa7c1bbe95a.png)

**Comment by bocharsky-bw** [comment]
Yeah, it happens randomly... sometimes I need to repeat the navigation several times too.

**Comment by maximivanov** [comment]
Doesn't seem to be PHP 7 specific issue. I can reproduce the problem following steps by bocharsky-bw with PHP 5.6.23, OS X, Symfony 3.2.1

**Comment by javiereguiluz** [comment]
Reopening and kindly asking @nicolas-grekas to take a look at this because this looks like a very tricky bug. Thanks!

**Comment by bocharsky-bw** [comment]
Hm, seems it's due to this `@Cache` line I think: https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/BlogController.php#L40
Probably this bug relates to the Symfony in general, not only to the Demo app.

**Comment by ciscolybon** [comment]
[Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot declare class AddCategoryIdImageToPosts, because the name is already in use

**Comment by javiereguiluz** [comment]
@xexu which PHP version and Symfony Demo version are you using?

**Comment by spacetraveller** [comment]
I get this all the time now, except with a different class name. Note that Dev does not exhibit the issue.

`PHP Fatal error:  Cannot declare class appProdProjectContainer, because the name is already in use in /var/www/html/myproject/var/cache/prod/appProdProjectContainer.php on line 6930`

I have to manually delete the cache folder in order to clear the cache.

**Comment by stof** [comment]
please open a new issue instead of commenting on an old closed issue (from before the 3.4 release).

**Comment by MusawerAli** [comment]
this error occur due to the twice of this code on the top
`use Symfony\Component\HttpFoundation\Request;`

Remove one `use\Request; `

**Comment by geetesh07** [comment]
![png](https://user-images.githubusercontent.com/70388959/124304545-78453e00-db81-11eb-9e1b-69d13019a69c.PNG)
I am getting this issue
