### ISSUE TITLE
Method findLatest move to service class

### ISSUE THREAD

**Issue by uikolas** [symfony/symfony-demo#415]
Sorry if this was already talked.
I'am looking at post repository class and findLatest method: https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Repository/PostRepository.php#L52 and for me doesn't look correct, to hold pagination in repository. Maybe pagination logic could be moved to service class? (Like PaginationService) or at least moved to controller. Opinions?

**Comment by javiereguiluz** [comment]
I always do pagination inside the repositories, so I don't consider it a bad practice ... but I'd love to read other opinions and recommendations about this. Thanks!

**Comment by javiereguiluz** [comment]
I'm closing this issue as "won't fix" because of the lack of feedback from the community. @uikolas I'm sorry this time your proposal didn't make it ... but please keep proposing changes and improvements because they usually get lots of attention from the community. Thanks!
