### ISSUE TITLE
symfony-demo/app/config/parameters.yml - should it be in the repository?

### ISSUE THREAD

**Issue by allyburns** [symfony/symfony-demo#42]
Is it not best practice to ensure parameters.yml is NEVER checked in?

I understand why it is here - to make sure it can be run out of the box, 
So many projects I see always mistakenly commit this file at first.

http://symfony.com/blog/new-in-symfony-2-3-interactive-management-of-the-parameters-yml-file

"As those parameters can be different on your local machine, your testing environment, your production servers, and even between developers working on the same project, it is not recommended to store it in the project repository. Instead, the repository should contain a paramaters.yml.dist file with sensible defaults that can be used as a good starting point for everyone."

Would it not be safer to just put the database settings straight into config.yml with a comment saying you are best copying parameters.yml.dist to parameters.yml and adding database settings there. Then have a commented out block in  config.yml 

    # help here explaining parameters.yml and parameters.yml.dist

    #       driver:   "%database_driver%"
    #       host:     "%database_host%"

This way it will run out the box, without a parameters.yml file.

 - { resource: parameters.yml } # this would need commented out too, with an explanation why.

Maybe I'm taking this too far, what are others thoughts?

**Comment by stof** [comment]
@allyburns putting DB credentials directly in config.yml is even worse. config.yml should not containmachine-specific settings.

@javiereguiluz what do you think about ignoring the parameters.yml file in the repo to follow the best practices, and relying on the installer to create the parameters.yml file (which is already supported by the ``symfony new`` command btw) ?

**Comment by allyburns** [comment]
@stof Yes, I realise that, I should have made it clear that it was maybe only okay as it was an Sqlite database with no password. Appreciate my initial idea maybe not the best.

     database_user: root
        database_password: null
        database_path: '%kernel.root_dir%/data/blog.sqlite'

In reflection, I'd much rather we rely on teaching users properly about parameters.yml.dist and using parameters.yml correctly.

**Comment by javiereguiluz** [comment]
@allyburns thanks for initiating this discussion and for understanding the reasons why we do what we do.

I think the best option would be the one proposed by @stof (create the `parameters.yml` dynamically after uncompressing the Symfony Demo contents). I'll prepare a PR soon.

By the way, keep in mind that most users will never see this repository. They execute `symfony demo` and they get the code, in which it's normal to have the `parameters.yml` file. They would only notice something strange if the see the `.gitignore` contents.

**Comment by devdrops** [comment]
My 2 cents - being a PHP developer and using Symfony 2 in my daily work:

@javiereguiluz I see your point; however, the Symfony Demo Application is, as stated at README.md, a _"reference application created to show how to develop Symfony applications following the recommended best practices."_, and periodically people like me and many others check and follow the news about Symfony, updates and more, through this repository, for a basis to learn more and more about Symfony 2.7.*. In short: people use this repository as a reference to learn and apply best practices for Symfony projects. So, IMHO I believe this is a strong argument to avoid versioning the parameters.yml file and, instead, include only the parameters.yml.dist file ;)

**Comment by marcoalbarelli** [comment]
+1 for a parameters.yml.dist file
I also use a htaccess.dist file that I normally check in to have it ready

**Comment by javiereguiluz** [comment]
Closing it as "fixed" now that #149 has been merged.
