### ISSUE TITLE
Driver error

### ISSUE THREAD

**Issue by Thibault34** [symfony/symfony-demo#423]
Hello,

When I go in http://localhost:8000/fr/blog/ I have error :
An exception has been thrown during the rendering of a template ("An exception occured in driver: could not find driver").

 Can you help me please ?

**Comment by voronkovich** [comment]
@Thibault34, see https://github.com/symfony/symfony/issues/21120

**Comment by stof** [comment]
you need to enable the sqlite extension, as the demo uses sqlite by default

**Comment by Thibault34** [comment]
Tanks you @stof

**Comment by javiereguiluz** [comment]
@Thibault34 let me reopen this issue because maybe we can apply an idea similar to #422 and show a better error message in the browser when you don't have SQLite enabled.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #452.
