### ISSUE TITLE
Access denied immediately that we modify the "Author email" field

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-demo#429]
We are currently protecting that [a post must be edited by its own author](https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L145) only, but when I'm creating/editing my own post, specifically the field "Author email" and I save the post, I receive immediately this message (403 Access Denied):

```
Posts can only be edited by their authors.
```
Sure, I've changed my post author and now it doesn't matching, so I've losted my own post, :( it looks weird.

My conclusion is that "Author Email" field is useless in this case, because we can't edit it never, so I propose remove it from `PostType` form, WDYT?

**Comment by voronkovich** [comment]
I think we should use a relation between post and author to check the edit permission.

**Comment by yceruto** [comment]
There is some reason currently why an post is not directly related to the user (i.e. `post.user_id`)?

**Comment by bocharsky-bw** [comment]
IIRC, the main reason why posts is not directly related to users is complexity for beginners

**Comment by yceruto** [comment]
@bocharsky-bw It's already done with Comment/Post, even actually, we are related Post/User and Comment/User indirectly throught `authorEmail` field which IMHO makes things more complicated for the beginner, because we need really this relationship:

https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/BlogController.php#L92

    $comment->setAuthorEmail($this->getUser()->getEmail());
    // vs
    $comment->setAuthor($this->getUser());

https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L76

    $post->setAuthorEmail($this->getUser()->getEmail());
    // vs:
    $post->setAuthor($this->getUser());

https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Entity/Post.php#L170

    return $user->getEmail() === $this->getAuthorEmail();
    // vs:
    return $user === $this->getAuthor();

https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L125
https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L145

     if (null === $this->getUser() || !$post->isAuthor($this->getUser())) {
     // vs:
     if (!$post->isAuthor($this->getUser())) {

https://github.com/symfony/symfony-demo/blob/master/app/Resources/views/blog/post_show.html.twig#L52

    {% if app.user and post.isAuthor(app.user) %}
    // vs:
    {% if post.isAuthor(app.user) %}

and so on.

In the other hand, now we can filter the posts list by the logged user (https://github.com/symfony/symfony-demo/pull/428#issuecomment-272205368) so to do that currently we need:

https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L58

    $posts = ...->findBy(['authorEmail' => $this->getUser()->getEmail()], ['publishedAt' => 'DESC']);
    // vs:
    $posts = ...->findBy(['user' => $this->getUser()], ['publishedAt' => 'DESC']);

What do you think now?

I would like to know the opinion of some member on this matter ;)

**Comment by voronkovich** [comment]
I totally agree with @yceruto.

**Comment by yceruto** [comment]
Here is a Pre-PR to analyze the changes https://github.com/symfony/symfony-demo/commit/d7c5e5f6700e828740daf3084f692d75b44cb0c1 ;)

**Comment by bocharsky-bw** [comment]
@yceruto Yes, I see your point, and I'm fine with these changes.

**Comment by yceruto** [comment]
Closing thanks to https://github.com/symfony/symfony-demo/issues/434
