### ISSUE TITLE
Unexpected locale path after login successful

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-demo#436]
Hi there, I found a problem when the user change the language in login page, it change but doesn't keep after login. This occurs whenever the user is redirected to login page because it's not fully authenticated.

It happen because the default Target Path Behavior (in Security component) which retains the information of the last request URI in a session variable and upon a successful login, the user is redirected to this path (with the old locale), changing it again.

One possible solution could be set `always_use_default_target_path: true` to generate the default target path with the current locale? or add the `_target_path` parameter into login form. i.e.:

    <input type="hidden" name="_target_path" value="admin_index"/>

Any suggestion?

**Comment by javiereguiluz** [comment]
Even if this issue is real, I'd say it's an edge case that we shouldn't fix in the demo application.

**Comment by yceruto** [comment]
Won't fix, agreed!
