### ISSUE TITLE
Add tags to posts with many-to-many relation

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-demo#44]
Hi there!
What about to add `Tag` entity relates **many-to-many** with `Post`?
I think it will be very useful for beginners.
I vote :+1: for it. What do you think?

**Comment by King2500** [comment]
:+1:

**Comment by tamedo** [comment]
:+1:

**Comment by javiereguiluz** [comment]
I also think it's a good idea to add this many-to-many relation example. @bocharsky-bw thanks for proposing it!

**Comment by JulienItard** [comment]
Or maybe many-to-many Categories instead? And, with it we could show render(controller()) in view to render categories list on sidebar with a posts count ?

**Comment by bocharsky-bw** [comment]
@JulienItard Commonly the *categories* more global than *tags* and better relate `Category` with `Post` with one-to-many relation.
What about `render(controller())`, it could be used for tags too, for example, to render tags list (or tags cloud) in sidebar with a posts count.

**Comment by b-durand** [comment]
So category or tags?

**Comment by JulienItard** [comment]
:+1: tags

**Comment by voronkovich** [comment]
Tags, because it will be able to add simple example how to use data transformers (Form).

**Comment by cyphos1973** [comment]
Yes for tags with entity relates many-to-many
plse
thanks

**Comment by andesk** [comment]
For tags, probably a lot of code could be reused from http://symfony.com/doc/current/cookbook/form/form_collections.html ? ;)

**Comment by ccab** [comment]
It could be interesting to show a nice js experience to the tags with the select2 library

**Comment by bocharsky-bw** [comment]
I'm more inclined to the [harvesthq/chosen](https://github.com/harvesthq/chosen) library for this feature.

**Comment by cordoval** [comment]
not sure why this was not been added ...

**Comment by xabbuh** [comment]
Apparently nobody opened a pull request yet.

**Comment by rasanga** [comment]
I am going to create a PR for this

**Comment by yceruto** [comment]
Should be closed (https://github.com/symfony/symfony-demo/pull/447)

**Comment by javiereguiluz** [comment]
Closed as fixed 🎉

**Comment by bogdaniel** [comment]
i used a data transformer with select2 and worked smoothly no problems :D
