### ISSUE TITLE
Create a security voter to restrict post edition

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#440]
### The idea

Develop a very simple security voter that grants/rejects `EDIT` permission on blog posts in the backend.

### Reasons

* The backend assumes that you only see/edit your own posts ... but if you play with the URL parameters, you can access the edit/show page of any post. Let's add a check to prevent users from editing other people's posts.
* Voters are cool and recommended by Symfony ... but we don't have any yet.

**Comment by yceruto** [comment]
> but if you play with the URL parameters, you can access the edit/show page of any post.

The `$post->isAuthor($user)` check doesn't avoid that?

**Comment by javiereguiluz** [comment]
@yceruto yes! Does it make sense to move that to a global check via a voter?

**Comment by yceruto** [comment]
@javiereguiluz it makes sense to check this via voter, but I think we need https://github.com/symfony/symfony-demo/pull/434 then to make it easier to implement.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #442.
