### ISSUE TITLE
Improve the functional tests

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#445]
As pointed by @stof, in [this comment](https://github.com/symfony/symfony-demo/pull/444#discussion_r96828839) at least one of our tests modifies the state of the testing database.

We should improve this by automatically resetting the testing database before each test. In our case this can't be very complex to do because the database is just a file called `var/data/blog_test.sqlite`

**Comment by yceruto** [comment]
At now neither test change the DB status, because just we check the response content/status for now, but I'm sure that we need that since there is uncovered actions that change the DB status, for example:

* "Create a new post/comment successfully"
* "Edit an existent post successfully"
* "Delete an existent post successfully"

So my vote :+1:

**Comment by dmaicher** [comment]
I propose this PR (https://github.com/symfony/symfony-demo/pull/459) that uses my bundle https://github.com/dmaicher/doctrine-test-bundle to have very simple database isolation for all tests :blush: I'm using this bundle in several private and professional projects with mysql, sqlite and postgres - works very nicely.

I changed the tests slightly so first Post 1 is deleted and in the next test its edited. Just to show that all tests are running within database level transactions now that are rolled back at the end of the test.

What do you think?

**Comment by stof** [comment]
@yceruto deleting an existing post successfully changes the DB (at least I hope it does)

**Comment by yceruto** [comment]
@stof sure, but before https://github.com/symfony/symfony-demo/pull/459 it didn't happen: https://github.com/symfony/symfony-demo/pull/444#discussion_r97114702 so the post was never successfully removed.

**Comment by blackboxlabz** [comment]
Hello there! It is a great piece of information for improving functional tests I hope this satisfies the requirements  Kindly post some tips regarding <a href="https://blackboxlabz.com/software-functional-testing/"> Functional Testing Services </a>
