### ISSUE TITLE
[RFC] Add a new "name" field to User entity

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-demo#446]
Following @javiereguiluz's comment: https://github.com/symfony/symfony-demo/pull/439#discussion_r96436908

> for the users I'd like to display people names instead of emails (so we might need to add a field in the user entity).

There is any privacy/security reasons to do that?
This should be named `name` or `fullName`?

What do you think?

**Comment by javiereguiluz** [comment]
I agree with adding a `fullName` property in the `User` entity ... but not any other property, to keep things simple.

**Comment by yceruto** [comment]
:+1:

**Comment by yceruto** [comment]
This property should be optional or mandatory?

**Comment by javiereguiluz** [comment]
Closing it as fixed by #457.
