### ISSUE TITLE
PHP CS Fixer triyng to fix files under "var/cache/" folder

### ISSUE THREAD

**Issue by mstrom** [symfony/symfony-demo#462]
When I run PHP CS Fixer it trying to fix all cache files located under var/cache/* folder

I assume that var/cache/ folder should be ignored?

**Comment by bocharsky-bw** [comment]
You're right, `var/` folder should be ignored. However, it's ignored for me.

Could you try to pull the latest changes from master branch and do `composer install`? Does it fix your problem?

**Comment by mstrom** [comment]
Looks like i run php-cs-fixer incorrectly 

>  php-cs-fixer fix . 

will fix files under /var/cache

>  php-cs-fixer fix`

works as intended

**Comment by javiereguiluz** [comment]
Closing it as "fixed" then. Thanks!

**Comment by stof** [comment]
yeah, if you pass a path to the command, it fixes it, ignoring the paths defined in the config file
