### ISSUE TITLE
User not implementing Serializable in symfony-demo?

### ISSUE THREAD

**Issue by ptrm04** [symfony/symfony-demo#494]
According to http://symfony.com/doc/current/security/entity_provider.html#what-do-the-serialize-and-unserialize-methods-do the User class should implement `Serializable` - why does the symfony-demo not implement it on the User class?

**Comment by voronkovich** [comment]
@ptrm04, you're right, the `User` class should implement the `Serializable` interface. Could you please create a PR to fix this issue (just copy and paste code from the Symfony's tutorial)?

**Comment by ptrm04** [comment]
@voronkovich thanks for the confirmation, will do.

Symfony Demo (and any app where you don't need to serialize anything in particular) will actually work just fine without implementing the `Serializable` interface - why is that? And since it is working, do we **_really_** need it?

**Comment by ptrm04** [comment]
Quick check revealed that if you don't implement `Serializable` it will basically put everything in the session i.e. email anna_admin@... et al. can be found in the session. So would the purpose of implementing `Serializable` is to strictly decide what needs to be serialized? Otherwise everything will go in?

**Comment by javiereguiluz** [comment]
This is one of the multiple things that I don't like about the Symfony Security. Why should we do this ourselves? Shouldn't Symfony by default apply some smart serialization and force you to define it yourself only in advanced/complex cases?

**Comment by stof** [comment]
@javiereguiluz serializing a PHP object which is not Serializable works fine in most cases.
but there is one case where it causes issues: serializing a Doctrine Proxy which has not yet been initialized, because the internal PHP serialization logic will not trigger the proxy initialization. But when implementing ``Serializable``, the logic calls the method, which loads the proxy data.

**Comment by stof** [comment]
And note that this is true any time you serialize a Doctrine entity, not only for the Security component (and it is documented in the Doctrine doc IIRC)

**Comment by javiereguiluz** [comment]
Thanks for the explanation. But I wonder why should we document this, implement this, etc.  ... instead of changing this. It doesn't feel right. It's a burden that we impose to our users ... and for something a critical as security.

**Comment by voronkovich** [comment]
@ptrm04, you're right. As mentioned [here](https://dzone.com/articles/how-correctly-work-php):

> However, it follows field references, so if you're referencing an ORM or framework objects from your own serialized ones, you're likely to grab the whole library with it

So, it's better in most cases to specify what to serialize programmatically.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #495.
