### ISSUE TITLE
Add SQLite requirement

### ISSUE THREAD

**Issue by JulienItard** [symfony/symfony-demo#51]
We should add a Requirements section on the README and add PHP SQLite extentsion.

**Comment by javiereguiluz** [comment]
We recently added a Composer dependency for this: https://github.com/symfony/symfony-demo/blob/master/composer.json#L11

But I think you are right and we should add a note about this in the README.

**Comment by JulienItard** [comment]
Ok i'll do it

**Comment by javiereguiluz** [comment]
Fixed in #52
