### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by jkufner** [symfony/symfony-demo#512]
Hello,
every application based on SQL database must deal with database migrations during upgrades. It would be nice to have few migrations in the demo application to show how they should be done.

**Comment by apetitpa** [comment]
While I like the idea, I also think it would add complexity to the demo app since one would have to execute migrations before beeing able to use the app which could be disturbing for a complete beginner. And I believe the application have to stay as simple as possible and should work out of the box just by doing `composer install` and `php bin/console server:start`.

**Comment by jkufner** [comment]
The migrations may not be mandatory. Then the complete beginner could skip them and still get a working demo. However, a part of the demo would not work until the migrations are done.

**Comment by javiereguiluz** [comment]
@apetitpa if we make this change, the migrations would be optional as explained by @jkufner.

The basic premise of the Symfony Demo app, which we defined on day one and we'll enforce it forever, is that the app must be installed and ready in 10 seconds without the need to do anything (configure options, load fixtures, compile assets, answer to questions, etc.)

**Comment by apetitpa** [comment]
@javiereguiluz @jkufner I see what you mean and I agree with you. I have started something but I can't figure out what to migrate ? Do you have an idea of what could a good example ?

**Comment by javiereguiluz** [comment]
@apetitpa instead of thinking something new to migrate ... maybe we can make a "migration from the past". @yceruto recently added a `fullName` property to the `User` entity. So maybe we can do a migration for that change. See #457 for details.

**Comment by jkufner** [comment]
The migrations may be already performed in the database file. So we can have migration of some recent change and also some small "useless" migration to increase column size, add index, or something.

**Comment by yceruto** [comment]
I agree with this comment https://github.com/symfony/symfony-demo/issues/512#issuecomment-287773851 but, If we add a new property into migration file, then it's not optional and will be mandatory run the migrations to avoid mapping errors at runtime.

**Comment by javiereguiluz** [comment]
That's why I proposed to make a migration from the past. Let's imagine that our User entity doesn't have "fullName" and let's add it. The app must have the final definitive DB structure, so every migration must have been applied.

**Comment by apetitpa** [comment]
Since the fullName property cannot be null, what should be the default value in the migration ? Assuming that this migration would have been applied on a database containing existing users.

**Comment by jkufner** [comment]
> Since the fullName property cannot be null, what should be the default value in the migration?

`username`

**Comment by javiereguiluz** [comment]
I'm closing this for now because we tried to implement this and we failed. Besides, unlike other frameworks, database migrations are not prominently promoted in Symfony Docs or best practices. Let's fix that first and then we can add an example here. Thanks!
