### ISSUE TITLE
form_row block override in form theme does not work for checkbox

### ISSUE THREAD

**Issue by emodric** [symfony/symfony-demo#515]
I tried adding an override for `form_row` block in `app/Resources/views/form/layout.html.twig`:

```twig
{% block form_row %}
    MY OVERRIDE START

    <div>
        {{- form_label(form) -}}
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
    </div>

    MY OVERRIDE END
{% endblock %}
```

I also added a boolean property to one of the entities (for example Post), and corresponding checkbox field to PostType.

It turns out that `form_row` block override is not applied to Checkbox form type, and I couldn't find the reason why.

This is not an issue in Symfony nor an issue with version of PHP. I tested on PHP 5.6, PHP 7.1 and both show this behaviour. I also tested on Sylius (with Symfony 3.2) and it works okay there, so I think it is related to something in this demo.

If this is intended, how do I make the checkbox form type use my `form_row` override?

Thanks!

**Comment by emodric** [comment]
It turns out this is due to the fact that more specific block overrides are used from `bootstrap_3_layout.html.twig`, specifically, `radio_row` and `checkbox_row`.

Is there a way to tell Symfony forms not to use globally defined themes, but only those specified in theme template?

**Comment by javiereguiluz** [comment]
I'd say it's not possible, but let's ask to a real Symfony Forms expert:  @HeahDude could you confirm or deny this? Thanks!

**Comment by HeahDude** [comment]
Hello @emodric, you need to override the template when you don't want to use a global one, see http://symfony.com/doc/current/form/form_customization.html#referencing-blocks-from-inside-the-same-template-as-the-form for an example of "picking" some specific blocks from a template.

**Comment by emodric** [comment]
@HeahDude Yes, I'm aware of that, but it would be quite useful to specify in `form_theme` tag call that you DO NOT want to apply globally defined form themes.

Our usecase is an administration interface for a layout management application built on top of Symfony framework, It can be installed and used on many full stack Symfony apps like eZ Platform, Sylius and even this Symfony Demo app. We have a form theme that skins many forms in the administration interface and we extended from `form_div_layout.html.twig` to get the basic look & feel from which we could build upon. However, if some themes are defined globally, like `bootstrap_3_layout.html.twig` here, they override some behaviour, if they have some blocks not available in `form_div_layout.html.twig`.

We fixed it by overriding the blocks ourselves, but the issue is that we cannot control what themes may be activated globally. Therefore, to build the administration interfaces that are visually completely different from the rest of the app, I think it would be good to have an option to disable usage of global themes per form.

**Comment by HeahDude** [comment]
@emodric I think the easiest would then to maintain your own template files, because you can't control that actually, and those framework files may evolve in the future and potentially break your app.

**Comment by emodric** [comment]
@HeahDude Yes, sure, but that's a separate issue. Because, even if we maintain our separate files, we would need to define EVERY possible block in our form theme to stop the globally defined themes from interfering.

A simple example:

If I want my admin interface to have a sepecific design for every form row, I would define a `form_row` block.

However, if a globally defined theme specifies an override for a specific row, for example `number_row`, it would be applied before my own `form_row` because it is more specific and it would break my admin design, with no easy way to detect it or disable it, apart from overriding the `number_row` block myself in my theme.

**Comment by HeahDude** [comment]
>you DO NOT want to apply globally defined form themes

This is a feature that should be added in symfony core.

>even if we maintain our separate files, we would need to define EVERY possible block in our form theme to stop the globally defined themes from interfering.

Indeed, but sadly there is no other way for now.

**Comment by emodric** [comment]
> This is a feature that should be added in symfony core.

Yes, that is my point ;)

My idea would be to add an `only` keyword to `form_theme` tag, similar to `include` tag:

`{% form_theme form with ['common.html.twig', 'form/fields.html.twig'] only %}`

If that sounds good, maybe I could work on it to create a PR?

**Comment by HeahDude** [comment]
`only` sounds good to me, any PR would be welcome, thanks!

**Comment by emodric** [comment]
@HeahDude PR created at https://github.com/symfony/symfony/pull/22610

**Comment by javiereguiluz** [comment]
Let's close this issue because it's not actionable for the Symfony Demo app. Thanks!
