### ISSUE TITLE
Implement a Social Sign On/Social Login solution

### ISSUE THREAD

**Issue by wcomnisky** [symfony/symfony-demo#524]
Hey guys,

Do you think it's a good idea to implement a Social Login alternative?

I'm keen to work on this if you agree it worthwhile to be added to the project. 

To avoid being just another complexity we could add it as optional. If the keys (for the integration) were provided it will be enabled. By default it will be disabled.

**Comment by javiereguiluz** [comment]
In my opinion, it's *not* a good idea to implement a "Social Login" feature because in Symfony apps it's much more complicated than it should be. It's not something to be proud and it's not something we should show.

But let's wait to hear more opinions about this.

**Comment by jkufner** [comment]
Social login should have its own demo.

**Comment by stof** [comment]
@bocharsky-bw Registering an OAuth application requires providing a callback URL. So we cannot create one valid for all people running the demo.
Thus, we should not provide the application secret in the repo (this would go against the goal of the demo of showing best practices), making it hard to enable it out of the box

**Comment by bocharsky-bw** [comment]
@stof What about OAuth callback URL, `bin/console server:run` always runs on http://127.0.0.1:8000 by default, but you're right, we probably can't rely on users hoping they won't change this URL. And agree about application secret.

**Comment by 20uf** [comment]
In my humble opinion this is not a good idea because the purpose of the demo is only to present the good practices with simple basics.

**Comment by XPanel** [comment]
Could not find package symfony/symfony-demo with stability stable in a version installable using your PHP version 7.0.21.

Could you update it to the latest php 7.0.XX

**Comment by bocharsky-bw** [comment]
@XPanel You can tweak this version in `composer.json` manually, see `config.platform.php` value, but this project should be compatible with`5.5.9`. Or are you trying to install `symfony/symfony-demo` as a dependency with `composer require`?

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because of its technical complications and because this feature is not the strongest suit of Symfony. Thanks!
