### ISSUE TITLE
Tests fail for AddUserCommand if shell is not a TTY

### ISSUE THREAD

**Issue by dzuelke** [symfony/symfony-demo#530]
This can happen in certain CI environments etc.

To reproduce: `sh -c 'vendor/bin/phpunit tests/AppBundle/Command/' < /dev/null 2>&1`:

```
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

..stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
E
…
```

The culprit is the "hidden" mode for the password field. I am not sure whether this is actually a bug in `Symfony\Component\Console\Helper\QuestionHelper::getHiddenResponse()`, where the error is triggered by all those `shell_exec` calls, or whether the command (or its test) should conditionally not set that hidden mode.

Pinging @nicolas-grekas for insight :) Also pinging @dmaicher who introduced the tests in #480.

**Comment by dmaicher** [comment]
The warnings indeed come from `QuestionHelper::getHiddenResponse()` :cry: Not sure if we can or should fix it in the tests here somehow or if it should be reported on `symfony/symfony`? @nicolas-grekas ?

**Comment by dzuelke** [comment]
Symfony 3.3 has https://github.com/symfony/symfony/pull/20885 for that but not sure if that'd even be the right workaround?

Maybe the console tester should call or handle that somehow?

**Comment by dzuelke** [comment]
Ping @nicolas-grekas :)
