### ISSUE TITLE
Unit test BlogControllerTest::testNewComment failing 

### ISSUE THREAD

**Issue by wcomnisky** [symfony/symfony-demo#554]
Tested against latest changeset on master: 46824f1
PHP 7.1.4-1

<pre>
$ ./vendor/bin/phpunit 
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

...............F......................

Time: 10.56 seconds, Memory: 20.00MB

There was 1 failure:

1) Tests\AppBundle\Controller\BlogControllerTest::testNewComment
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Ubi est audax amicitia Abnobas sunt hilotaes de placidus vita Teres talis saepe tractare de camerarius flavum sensorem Sunt accentores vitare salvus flavum parses Bassus fatalis classiss virtualiter transferre de flavum Ubi est barbatus nix Pellentesque et sapien pulvinar consectetur Urna nisl sollicitudin id varius orci quam id turpis Nulla porta lobortis ligula vel egestas Ut eleifend mauris et risus ultrices egestas
+Bassus fatalis classiss virtualiter transferre de flavum Sunt accentores vitare salvus flavum parses In hac habitasse platea dictumst Teres talis saepe tractare de camerarius flavum sensorem Ut suscipit posuere justo at vulputate Potus sensim ad ferox abnoba Curabitur aliquam euismod dolor non ornare Pellentesque et sapien pulvinar consectetur Nunc viverra elit ac laoreet suscipit

/home/william/dev/github/symfony-demo/tests/AppBundle/Controller/BlogControllerTest.php:94

FAILURES!
Tests: 38, Assertions: 71, Failures: 1.
</pre>

**Comment by dmaicher** [comment]
For me the tests on master are passing just fine:

```
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

......................................

Time: 14.51 seconds, Memory: 26.00MB

OK (38 tests, 71 assertions)

**Comment by voronkovich** [comment]
@wcomnisky, try to disable `DAMADoctrineTestBundle`.

**Comment by dmaicher** [comment]
@voronkovich why would that help?

**Comment by wcomnisky** [comment]
I couldn't retest yet to confirm but I think there's relation with the issue #556

**Comment by dmaicher** [comment]
@wcomnisky is the test still failing with the latest composer changes on master?

**Comment by dmaicher** [comment]
I guess this can be closed then?

**Comment by wcomnisky** [comment]
Confirmed!

<pre>
$ ./vendor/bin/phpunit 
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

......................................

Time: 11 seconds, Memory: 22.00MB

OK (38 tests, 71 assertions)
</pre>
