### ISSUE TITLE
Sometimes you use @return, @param (in docblock annotation), somethimes you don't. What is best practice?

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-demo#565]
or is it unimportant?

@param and @return in controller:
https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L120

No @param and @return in controller:
https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L120

You use @param and @return in Utils everywhere.

You use @param and @return in public function, not use in private.
https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Repository/PostRepository.php

**Comment by elkuku** [comment]
And sometimes there are no docblocks at all....

I'd love to see nice dockblocks especially since this is a demo application - even if it's not a "Symfony core standard" :wink:

**Comment by javiereguiluz** [comment]
@sruj this is a good question ... which doesn't have a simple answer!

* In November 2017 we'll update this app to Symfony 4.x and PHP 7.1 ... then we'll remove ALL PHPDoc and we'll use type-hints for arguments and result types.
* At the moment, the policy is:
  * Add PHPdoc for params and return types ... but not for thrown exceptions ...
  * ... except for private properties/methods/functions ...
  * ... and except when the PHPdoc is trivial
