### ISSUE TITLE
Manage frontend dependencies properly

### ISSUE THREAD

**Issue by apetitpa** [symfony/symfony-demo#583]
There is something I'd like to work on but before I need your opinion because I'm afraid it might be out of the scope of this application or too complicated for beginners.

Currently, frontend dependencies are just put in the web folder (bootstrap, jquery etc) but in real life these have to be managed properly (eg: http://symfony.com/doc/current/frontend/bower.html). Since Assetic is no longer used I would suggest using npm and gulp to do so and maybe create a frontend folder or something like that. What do you think ?

Of course this would require having npm installed but I think nowadays it's not something so crazy when working on a web project and we could still keep dependencies in the project so it would still work out of the box.

**Comment by mstrom** [comment]
[Bower](https://github.com/bower/bower) suggests:

> ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

**Comment by apetitpa** [comment]
@mstrom Indeed, this is why I recommended to use npm and gulp. I just linked the Symfony documentation to show an example.

**Comment by javiereguiluz** [comment]
In a few days (possibly next week) we're going to finally publish the new Symfony solution to manage web assets with JavaScript. I guess it will make sense to use that in this application.

**Comment by javiereguiluz** [comment]
I'm closing this in favor of #585 because the mentioned tool will finally be released next week 🎉
