### ISSUE TITLE
Manage application assets with the new Symfony asset manager

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#585]
Next week Ryan will publish his new project to manage web assets in Symfony applications. I propose to start using it in the Symfony Demo right away. Although it's new, it's pretty stable and it has been tested in several real Symfony apps.

The only thing to keep in mind is that the generated CSS and JS files must be committed to the repository to keep our promise that this app works out of the box without configuring anything or executing any command.

I'll take care of this issue because I have already worked with this package, so hopefully I can integrate it quickly. Thanks!

**Comment by stof** [comment]
what is this asset manager doing ?

**Comment by javiereguiluz** [comment]
I don't understand your comment ... but OK, it's not an asset manager ... is a helper for the real asset manager, which is Webpack 😁

**Comment by stof** [comment]
Well, you say "use the new asset manager". Having some kind of description of what this project does would be a good idea when you open an issue asking to use it (and unlike Encore, I don't have pre-release access to it, so I need to ask when you tease us)

**Comment by javiereguiluz** [comment]
@stof there's been a HUGE misunderstanding between us: I'm talking about Encore in this PR, not about another unannounced tool 😄   I didn't want to mention the real name (Webpack Encore) before Ryan unveiled it ... so I said "asset manager" ... but that's wrong, because Encore is "a Webpack manager".

**Comment by stof** [comment]
hmm, I missed the fact that this issue was opened before the release of Encore. I saw the issue after it (when reviewing the PR adding Encore).

I suggest closing this issue then, as the PR is merged (unless you want to polish the documentation about using Encore in the demo first)

**Comment by javiereguiluz** [comment]
Closing it as fixed by #589 and #593.
