### ISSUE TITLE
The Lato font is imported twice

### ISSUE THREAD

**Issue by stof** [symfony/symfony-demo#590]
the resulting CSS loads Lato twice (and with different weights being loaded btw):

- we load the font explicitly from a local install, using the `lato-font` npm package
- bootswatch loads the font by adding a `@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic)` in the CSS

**Comment by javiereguiluz** [comment]
If someone provides a solution for this, please remember that the app must work when you don't have an Internet connection, so we can't rely on Google's web fonts only. Thanks.

**Comment by stof** [comment]
Yeah, I would favor avoiding the `@import` rule, but I don't know how to avoid this output from bootswatch without altering the bootswatch source (which is a no-go as we install it from npm)

**Comment by javiereguiluz** [comment]
[This StackOVerflow question](https://stackoverflow.com/questions/34772357/bootstrap-css-without-google-fonts-2-bootswatch) could help us here:

> The latest Bootswatch versions (> 3.3.6.1) introduce a SASS variable $web-font-path that you can override and set to an empty value:
>
> $web-font-path: '';

**Comment by javiereguiluz** [comment]
Closing it as fixed by #605.
