### ISSUE TITLE
Form types should be in Form/Type folders

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#6]
**[in src/AppBundle/Form](https://github.com/javiereguiluz/symfony-demo/blob/898ee786f5ae5823725f23fa9d93bb7e0067d0a9/src/AppBundle/Form#L0)**

> Two form types have been found outside Form/Type folder

```

src/AppBundle/Form/
├── CommentType.php
└── PostType.php
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1bef6f83-ed09-42f0-8f70-ae8044936fe9/analyses/1)_

**Comment by weaverryan** [comment]
I'm kind of meh on this. How much non-form type stuff will a normal user have? It seems like an extra directory to me

**Comment by javiereguiluz** [comment]
The reasoning for this is that in the form folder we can put four different things:

  * Custom **form types**
  * Custom **data transformers**
  * Custom **choice lists**
  * Custom **event listeners**

In the future, this Symfony Demo application will grow to to show an example of these four things, so we'll probably need that directory. However, this will happen in some time, so I think it's safe to close this issue for now as *won't fix* and reconsider it in the future.

**Comment by weaverryan** [comment]
very good idea Javier!

**Comment by iifast2** [comment]
> **[in src/AppBundle/Form](https://github.com/javiereguiluz/symfony-demo/blob/898ee786f5ae5823725f23fa9d93bb7e0067d0a9/src/AppBundle/Form#L0)**
> 
> > Two form types have been found outside Form/Type folder
> 
> ```
> 
> src/AppBundle/Form/
> ├── CommentType.php
> └── PostType.php
> ```
> 
> _Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1bef6f83-ed09-42f0-8f70-ae8044936fe9/analyses/1)_

i did this using symfony 3.4.x and really helpfull.
