### ISSUE TITLE
Could not find package symfony/symfony-demo with stability stable.

### ISSUE THREAD

**Issue by XPanel** [symfony/symfony-demo#609]
hello,
when I run this command line:
composer create-project symfony/symfony-demo symfony-demo

I receive this error:
[InvalidArgumentException]
  Could not find package symfony/symfony-demo with stability stable.

I have php 7.1.7, the same error in php 7.0.21
Could you update it to the latest PHP?

**Comment by bocharsky-bw** [comment]
Hm, I wonder is it due to `config.platform.php` locked version or `"php": ">=5.5.9"` in require section?

**Comment by xabbuh** [comment]
The package is simply not registered on packagist.org. :)

**Comment by bocharsky-bw** [comment]
I was pretty sure it's registered. Any reasons do not register it? `composer create-project` is a good alternative way to install it I think

**Comment by javiereguiluz** [comment]
@bocharsky-bw moreover, the Symfony Installer is being deprecated, so the recommended way to install this project will be through `composer create ...`, so it must work!

@fabpot could you please register the Symfony Demo as a package on Packagist.org? Thanks!

**Comment by fabpot** [comment]
@javiereguiluz Done

**Comment by javiereguiluz** [comment]
Thanks!  Closing as fixed because:

* The packages exists at https://packagist.org/packages/symfony/symfony-demo
* The command `composer create-project symfony/symfony-demo symfony-demo` works now. If you see any problem, execute `composer clear-cache` because the package is very recent.
