### ISSUE TITLE
Attempted to call an undefined method named "newInstance" of class "Swift_Message".

### ISSUE THREAD

**Issue by XPanel** [symfony/symfony-demo#610]
in src/AppBundle/EventListener/CommentNotificationSubscriber.php (line 94) 

replaced:

```php
        $message = \Swift_Message::newInstance()
            ->setSubject($subject)
            ->setTo($post->getAuthor()->getEmail())
            ->setFrom($this->sender)
            ->setBody($body, 'text/html')
        ;
```

to this code:

```php
        $message = new \Swift_Message();
        $message->setSubject($subject)
            ->setTo($post->getAuthor()->getEmail())
            ->setFrom($this->sender)
            ->setBody($body, 'text/html')
        ;
```

**Comment by bocharsky-bw** [comment]
Good catch 👍 

@XPanel Do you want to create a PR?

**Comment by bocharsky-bw** [comment]
Btw, did you update `symfony/swiftmailer-bundle` to 3.0 to see this error or did you just do `composer install`?

**Comment by XPanel** [comment]
updated to 3.0

**Comment by bocharsky-bw** [comment]
This update holds BC breaks, that's why we require `"symfony/swiftmailer-bundle": "^2.3"` which means do not upgrade major version. This is unsupported use case and it's up to you to make those changes if you manually upgrade major version which supposes BC breaks.

**Comment by javiereguiluz** [comment]
@XPanel thanks for reporting this, but I agree with Victor. If this problem occurs when installing the Symfony Demo, then we must fix it. But if this happens when modifying it and installing version we don't support, then we can't fix it. So, let's close it.
