### ISSUE TITLE
Update this application to use Symfony Flex

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#616]
A while ago, I proposed to wait until Symfony 4.0 is released in November 2017 to update this application and start using Symfony Flex. Now I think that's a HUGE MISTAKE. If we wait until Symfony 4/Flex is released, we won't be able to discover and report issues or problems about Flex.

So now I propose to start using Symfony Flex in the Symfony Demo app a soon as possible. I'll submit a initial Pull Request about this very soon. Meanwhile, please don't submit any Pull Request for any feature because we won't be able to merge them. Thanks!

**Comment by uikolas** [comment]
What about leaving the old version in another branch?

**Comment by bocharsky-bw** [comment]
@uikolas Good idea I think 👍

**Comment by javiereguiluz** [comment]
@uikolas I'm sorry but I don't intend to create another branch for the old app, because we don't have resources to maintain both. I plan to release a new version of the app before moving into Flex, so you can always use that Git tag to see how was the app before Flex.
