### ISSUE TITLE
Mistake in AddUserCommand comment

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-demo#63]
Reminder https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Command/AddUserCommand.php#L151

- This method is executed before the interact() and the execute() methods.
+ This method is executed after the interact() and before the execute() methods.

**Comment by javiereguiluz** [comment]
@94noni thanks for reporting this issue. Indeed the help note was wrong. We've created a pull request in #64 to fix it.
