### ISSUE TITLE
Move BrowserKit to dev requirements?

### ISSUE THREAD

**Issue by garak** [symfony/symfony-demo#649]
I would propose a PR myself, but I want to be sure: is there any reason to keep "symfony/browser-kit" in "require" section of composer.json (instead of "require-dev")?
It looks like this application is never using anything in the `Symfony\Component\BrowserKit` namespace, so the only use I can see is for tests.

**Comment by yceruto** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Nice catch. This definitely looks like a mistake. Thanks!

**Comment by javiereguiluz** [comment]
Fixed by #650
