### ISSUE TITLE
What version of PHP is required?

### ISSUE THREAD

**Issue by ChrisLambertUK** [symfony/symfony-demo#660]
README.md states "Requirements: PHP 5.5.9 or higher"

composer.json starts with:
{
    "name": "symfony/symfony-demo",
    "license": "MIT",
    "type": "project",
    "description": "Symfony Demo Application",
    "require": {
        "php": "^7.1.3",

So which is it - PHP 7 or 5.5? Or am I confused?

**Comment by javiereguiluz** [comment]
@ChrisLambertUK the "master" branch requires PHP 7.1 ... but the latest stable release still requires PHP 5.5. We have a pending PR (#625) to update this when we release the new stable version based on Flex, which will be soon.

In summary:

* If you install this like: `symfony demo my_project` -> you need 5.5.9
* If you clone this repo and use the master branch -> you need 7.1.
