### ISSUE TITLE
phpunit fails on fresh install

### ISSUE THREAD

**Issue by tacman** [symfony/symfony-demo#664]
This is probably something really easy, but I'm missing it.  I've cloned the demo project, run composer install, copied phpunit.xml.dist to phpunit.xml, downloaded the latest phpunit, but running it fails:

tac@dev-survos-com:/var/www/symfony-demo$ phpunit
PHP Fatal error:  Class 'PHPUnit_Framework_BaseTestListener' not found in /var/www/symfony-demo/vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/PHPUnit/LegacyPHPUnitListener.php on line 7
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /usr/local/bin/phpunit:560
PHP   3. PHPUnit\TextUI\Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:141
PHP   4. PHPUnit\TextUI\TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:212
PHP   5. PHPUnit\TextUI\TestRunner->handleConfiguration() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:189
PHP   6. class_exists() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:921
PHP   7. spl_autoload_call() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:921
PHP   8. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:921
PHP   9. Composer\Autoload\includeFile() /var/www/symfony-demo/vendor/composer/ClassLoader.php:322
PHP  10. include() /var/www/symfony-demo/vendor/composer/ClassLoader.php:440
tac@dev-survos-com:/var/www/symfony-demo$ 

I've tried purging the cache, re-installing, etc. Am I doing something wrong?

**Comment by yceruto** [comment]
try with `./vendor/bin/simple-phpunit`?

**Comment by tacman** [comment]
Yep, that works perfectly.  Is that documented somewhere?  I swear I looked
before posting this, can couldn't find it.
