### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Symfony\Bridge\PhpUnit\TextUI\Command' not found 

### ISSUE THREAD

**Issue by XPanel** [symfony/symfony-demo#668]
hello,
when I run ./vendor/bin/simple-phpunit
I receive this error:
Fatal error: Uncaught Error: Class 'Symfony\Bridge\PhpUnit\TextUI\Command' not found in /var/www/vhosts/xxx.info/symfony/public_html/symfony-demo/vendor/symfony/phpunit-bridge/bin/.phpunit/phpunit-5.7/phpunit:5

also in  dev.log
[2017-10-05 14:07:02] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\Templ
ateController::templateAction","template":"default/homepage.html.twig","_locale":"en","_route":"homepage"},"request_uri":"http://xxx.info/symfony
-demo/public/","method":"GET"} []
[2017-10-05 14:07:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []

tested in php 7.1.10

**Comment by yceruto** [comment]
Have you tried upgrading the vendor?

**Comment by XPanel** [comment]
the same error after : composer update

**Comment by javiereguiluz** [comment]
Not sure what to do here because I can't reproduce this bug. The `vendor/bin/simple-phpunit` command works as expected for me (and for Travis CI servers too). Any idea?

**Comment by xabbuh** [comment]
The `simple-phpunit` script installs it own dependencies (when installing PHPUnit). You can try to remove its `vendor` directory too (e.g. just remove the `vendor/symfony/phpunit-bridge/bin/.phpunit` directory).

**Comment by XPanel** [comment]
Tested in another server with the same OS and php version and it is working
