### ISSUE TITLE
The composer install method in Readme.md is not setting up the demo properly.

### ISSUE THREAD

**Issue by coldwinds** [symfony/symfony-demo#67]
After run:

$ git clone https://github.com/symfony/symfony-demo
$ cd symfony-demo/
$ composer install

There is a missing bootstrap.php.cache problem.

So I have to run composer update to make the demo fully funcional.

**Comment by xabbuh** [comment]
Did `composer install` terminate successfully without any errors?

**Comment by coldwinds** [comment]
Hi, @xabbuh, There was no error. 

I just upgraded my composer, and did it again, everything works fine now.

Maybe it's because my composer's version is too old.

**Comment by javiereguiluz** [comment]
@coldwinds nice! I'm glad it's working now. As @xabbuh said, the `install` command should make the demo fully functional unless some error happened.
