### ISSUE TITLE
Add an example using an ajax request

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-demo#69]
Hello,

I think it can be useful to show a mini example of how Symfony deals with ajax request.
- Form the view with javascript code to the controller handling and sending json or html directly
- GET (and POST maybe) request(s)

Any thoughts?

**Comment by JulienItard** [comment]
I agree that's a good idea. Maybe could we use ajax when deleting post ?

**Comment by sebastianblum** [comment]
AngularJS example would be nice

**Comment by JulienItard** [comment]
I disagree with AngularJS because i think that it should stay a Symfony tutorial only.

**Comment by 94noni** [comment]
-1 for angular, it is not the purpose of the symfony demo

A simple use case with get (querying something simple) just to see the front code and back handling will be enough IMO

**Comment by 94noni** [comment]
Doing a mini ApiController and consume it from the front can be a simple implementation

And it could as well show how to build an api with a sort of rest concepts (basic concepts)

**Comment by b-durand** [comment]
:+1:

**Comment by hason** [comment]
:+1:

**Comment by anacona16** [comment]
+1

**Comment by peshi** [comment]
+1

**Comment by TomasVotruba** [comment]
:+1:

**Comment by JHGitty** [comment]
:+1:

**Comment by haithem-rihane** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Closing it as fixed by #173 and #613.

**Comment by TomasVotruba** [comment]
Thanks
