### ISSUE TITLE
file loading order in Kernel->configureRoutes

### ISSUE THREAD

**Issue by wasbait** [symfony/symfony-demo#780]
configuration load order prevents overriding of route configurations by environment
For example :
In production we want to use the HTTPS but not in DEV.
we can not set this config in routes / dev / routes.yaml

is it possible to load the route configuration files by environment after the global route configuration file ?

Thanks

**Comment by javiereguiluz** [comment]
This is controlled in the `configuredRoutes()` method of the `src/Kernel.php`. See https://github.com/symfony/demo/blob/693562c2e942c20e7866881f29a5afc2f2f89ae7/src/Kernel.php#L58-L68  We use the same code as [the default Symfony kernel](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/src/Kernel.php) but you can change the code in your own applications to fit your needs.

**Comment by javiereguiluz** [comment]
Closing because it seems that we can't do much about this.

**Comment by sebastianblum** [comment]
@wasbait did you try

```yaml
routes.yaml
app:
    prefix: /
    resource: ../src/Controlle
    schemes: ["%http_schema%"]
    type: annotation

packages/framework.yaml
parameter:
  http_schema: https

packages/dev/framework.yaml
parameter:
  http_schema: http

This should work for you

**Comment by wasbait** [comment]
thank you for your proposal sebastianblum
I modify the file kernel.php to load the configurations in the order that suits me
the idea of ​​this issue is to say that a feature in older versions no longer works, namely, the override of the configuration in the configuration files
Personally I think it's a small regression but nothing serious if you master configuration management

**Comment by stof** [comment]
@javiereguiluz I think we should change the recipe to load environment-specific routes last though

**Comment by wasbait** [comment]
I agree @stof

**Comment by javiereguiluz** [comment]
I disagree. That would be a huge BC break ... and also the current behavior is consistent with what we do to load the services/packages config:

```php
        $loader->load($confDir.'/{packages}/*'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{packages}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob');
        $loader->load($confDir.'/{services}'.self::CONFIG_EXTS, 'glob');
```
