### ISSUE TITLE
Update application translations

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-demo#83]
In #80 @b-durand finished translating the entire Symfony Demo application. Now we need to update all the existing translation files:

* [x] English (in #80)
* [x] French (in #80)
* [x] Spanish (in #82)
* [x] Russian (in #86)
* [x] Ukrainian (in #93)
* [ ] Romanian
* [x] Brazilian Portuguese (in #84)
* [x] German (in #89)
* [x] Czech (in #90)

If you plan to update any of the existing translations, please add a comment to let others know that you are working on that.

And if you want to translate the application into other languages, you are more than welcome to do that. Thanks!

**Comment by bocharsky-bw** [comment]
I could help with `Russian` and `Ukrainian` translations

**Comment by javiereguiluz** [comment]
@bocharsky-bw thanks! I've "assigned" those translations to you so others don't start working on them. But there is no hurry to finish them :)

**Comment by patricksebastien** [comment]
It is nice to have translations but I don't see where we can change it on the demo app. It would be nice to add a dropdown with the supported languages (of course the post will still be in English).

How to implement that?

**Comment by bocharsky-bw** [comment]
I like this idea.

**Comment by bocharsky-bw** [comment]
We need to add a dropdown list with available langs and add locale to each route.
@javiereguiluz what do you think?

**Comment by JulienItard** [comment]
i could work on it if everyone is ok.

**Comment by javiereguiluz** [comment]
I'm OK, but please, don't modify the routes to include the locale. Let's keep it as a query parameter to not complicate things much.

Anyway, let's wait for other people's opinions about this.

**Comment by bocharsky-bw** [comment]
:+1: for query parameter

**Comment by JulienItard** [comment]
Ok, i'll do it. Any more opinions ?

**Comment by patricksebastien** [comment]
Since many people will use this demo app as a learning tool (or even as a template), please be sure to include comments & try to use the best practice for making a i18n website. Merci beaucoup Julien.

**Comment by JulienItard** [comment]
Yep, i'll do my best.

**Comment by b-durand** [comment]
Best pratices is to have locale in the route :wink: [Check out the doc.](http://symfony.com/doc/current/book/translation.html#the-locale-and-the-url)

**Comment by javiereguiluz** [comment]
@b-durand strictly speaking, best practices are explained in the "Symfony Best Practices Book", not in the regular Symfony book ;)

Anyway, I don't know what to say. I want the demo application to have and show everything ... but at the same time I want to keep it simple and easy to understand. This is maybe an impossible to reach balance.

**Comment by bocharsky-bw** [comment]
@javiereguiluz Yes, you're tight, it'll be a hard to reach balance.
Maybe separate by different branches in order to make *slim* and *fat* Symfony Demo application will be a proper solution?

**Comment by JulienItard** [comment]
so ? By route or query parameter ?

**Comment by javiereguiluz** [comment]
I'm pinging @weaverryan to see if he can help us decide: Should we change all routes to include the `_locale` parameter or should we maintain the application as is and add the locale as a query parameter? Thanks.

**Comment by weaverryan** [comment]
Let's put it in the route, assuming a few things:

1) `/blog/` is still English, and `/es/blog` is used for other languages. In other words, the `_locale` is optional in the URL (follows apple.com, for example, and is a little more sophisticated)

2) I can't remember if this requires us to pass `_locale` in every route generation? I would love if it didn't require that :).

The query parameter just isn't realistic enough (even though it's cleaner).

**Comment by JulienItard** [comment]
If everyone is ok i'll do it.

@weaverryan 
 1) Ok !
 2) It doesn't require it, we can use global prefix in route.yml

**Comment by javiereguiluz** [comment]
I agree with @weaverryan's ideas.

**Comment by b-durand** [comment]
@javiereguiluz weaverryan said the same as me :wink:

**Comment by javiereguiluz** [comment]
@b-durand then I agree with your ideas too :)

**Comment by javiereguiluz** [comment]
Closing it as fixed. Thank you all for the great work!

**Comment by JulienItard** [comment]
:+1:

**Comment by cristi-contiu** [comment]
Sorry for the delay, I've just PRed the romanian translations.

**Comment by javiereguiluz** [comment]
@cristi-contiu thanks a lot! They've just been merged.
