### ISSUE TITLE
Executing script security-checker security:check [KO]

### ISSUE THREAD

**Issue by lagne142** [symfony/symfony-demo#886]
Hi, when I execute composer create-project symfony/symfony-demo, I got this error code

![prb](https://user-images.githubusercontent.com/44204580/48003596-29645380-e10f-11e8-837f-0185880bcec6.jpg)

Is there a solution for this problem ?
thank you

**Comment by javiereguiluz** [comment]
This may be a temporary network issue ... I've just run `./bin/console security:check` and it worked as expected. Can you reproduce the error or it was fixed? Thanks!

**Comment by lagne142** [comment]
Same problem when I execute the command php bin/console security:check

![prb2](https://user-images.githubusercontent.com/44204580/48054495-b2ca6300-e1ad-11e8-8b6a-1289c3642783.jpg)
